import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:privacy_gui/core/utils/logger.dart';
import 'package:privacy_gui/generated/subscriptions.g.dart';
import 'package:privacy_gui/usp/providers/usp_service_provider.dart';
import 'package:privacy_gui/usp/services/sse_connection_manager.dart';
import 'package:privacy_gui/usp/services/sse_manager.dart';
import 'package:privacy_gui/usp/services/sse_operation_awaiter.dart';
import 'package:privacy_gui/usp/services/usp_bridge_client.dart';

/// Provides [UspBridgeClient] instance — depends on [UspService].
final uspBridgeClientProvider = Provider<UspBridgeClient?>((ref) {
  final usp = ref.watch(uspServiceProvider);
  if (usp == null) return null;
  return UspBridgeClient(usp);
});

/// Singleton [SseManager] provider — NOT autoDispose.
///
/// Lives for the entire authenticated session. Composes:
/// - [SseConnectionManager] — SSE stream lifecycle
/// - [SseSubscriptionRegistry] — OBUSPA + bridge subscription tracking
/// - [SseEventRouter] — event demux by subscription_id
final sseManagerProvider = Provider<SseManager?>((ref) {
  final usp = ref.watch(uspServiceProvider);
  final bridge = ref.watch(uspBridgeClientProvider);
  if (usp == null || bridge == null) return null;

  final manager = SseManager(usp: usp, bridge: bridge);
  ref.onDispose(() => manager.dispose());
  return manager;
});

/// Reactive SSE connection state as a [Stream].
///
/// Converts the [ValueNotifier] in [SseConnectionManager] to a Riverpod
/// stream for UI consumption (e.g., connection indicator badge).
final sseConnectionStateProvider = StreamProvider<SseConnectionState>((ref) {
  final manager = ref.watch(sseManagerProvider);
  if (manager == null) {
    return Stream.value(SseConnectionState.disconnected);
  }

  final controller = StreamController<SseConnectionState>();
  void listener() {
    controller.add(manager.connection.connectionState.value);
  }

  manager.connection.connectionState.addListener(listener);
  // Emit initial value
  controller.add(manager.connection.connectionState.value);

  ref.onDispose(() {
    manager.connection.connectionState.removeListener(listener);
    controller.close();
  });

  return controller.stream;
});

/// Provides [SseOperationAwaiter] for async Operate commands (Ping, Traceroute).
///
/// Returns null if USP or SSE manager is not available.
final sseOperationAwaiterProvider = Provider<SseOperationAwaiter?>((ref) {
  final manager = ref.watch(sseManagerProvider);
  final usp = ref.watch(uspServiceProvider);
  if (manager == null || usp == null) return null;
  return SseOperationAwaiter(manager, usp);
});

/// Bootstrap provider — connects SSE and registers core subscriptions.
///
/// Watch this from the app shell to trigger SSE connection after login.
/// Core subscriptions are "always-on" while the app is connected.
final sseBootstrapProvider = FutureProvider<void>((ref) async {
  final manager = ref.watch(sseManagerProvider);
  if (manager == null) return;

  final usp = ref.watch(uspServiceProvider);
  if (usp == null || !usp.isAuthenticated) return;

  // Step 1: Purge stale OBUSPA subscriptions from previous sessions.
  // Browser refresh doesn't trigger dispose(), so old subscriptions
  // accumulate on the router and cause duplicate SSE notifications.
  try {
    final purged = await usp.purgeAllSubscriptions();
    if (purged > 0) {
      logger.d('[SSE Bootstrap] Purged $purged stale OBUSPA subscriptions');
    }
  } catch (e) {
    logger.w('[SSE Bootstrap] Failed to purge stale subscriptions: $e');
  }

  // Step 2: Connect SSE
  await manager.connect();

  // Step 3: Register core subscriptions (non-fatal on failure)
  //
  // Subscriptions auto-generated from YAML subscribe: blocks.
  // See subscriptions.g.dart (generated by usp-codegen).
  for (final (id, notifType, path) in coreSubscriptions) {
    try {
      await manager.registry.register(
        subscriptionId: id,
        notifType: notifType,
        referenceList: path,
      );
    } catch (e) {
      logger.w('[SSE Bootstrap] Failed to register $id: $e');
      // Non-fatal: SSE is additive, app continues with polling
    }
  }

  logger.d('[SSE Bootstrap] Complete — '
      '${manager.registry.activeIds.length} core subscriptions registered');
});
