  // This is generated by icon_map_checker.dart
  import 'package:flutter/widgets.dart';
  import 'package:equatable/equatable.dart';
  import 'package:linksys_core/utils/named.dart';
  
  enum LinksysIcons {
    calendarDefault,
		optionsDefault,
		copyDefault,
		qrcodeDefault,
		smsDefault,
		mailB,
		administrationB,
		priorityDefault,
		filterDefault,
		administrationDefault,
		profileRound,
		policyDefault,
		shareiOS,
		statusOn,
		statusOff,
		flagCanada,
		flagUK,
		flagUnitedStates,
		supportDefault,
		restartDefault,
		flagSouthAmerica,
		flagAsia,
		signalstrengthWired,
		signalstrength4,
		signalstrength0,
		signalstrength3,
		signalstrength2,
		signalstrength1,
		devicesDefault,
		nodesDefault,
		uploadDefault,
		downloadDefault,
		disableRound,
		healthDefault,
		settingsDefault,
		homeDefault,
		checkDefault,
		checkRound,
		helpRound,
		arrowDown,
		shieldDefault,
		chevronLeft,
		chevronRight,
		chevronUp,
		chevronDown,
		profileDefault,
		crossDefault,
		addDefault,
		bellDefault,
		showDefault,
		bellB,
		wifiDefault,
		hideDefault,
		refreshDefault,
		arrowRight,
		moreHorizontal,
		searchDefault,
		arrowLeft,
		clockRound,
		editDefault,
		arrowUp,
		infoRound,
		securityDefault,
		moreVertical,
		grabberDefault,
		crossRound,
		stopRound,
		radioOff,
		circleOn,
		shareDefault,
		bugDefault,
		dangerDefault,
		botDefault,
		playRound,
		pauseRound,
		ethernetDefault,
		signalstrengthWired2
  }
  
  const jsonLinksysIcons = {"calendarDefault": 0xea01,
		"optionsDefault": 0xea02,
		"copyDefault": 0xea03,
		"qrcodeDefault": 0xea04,
		"smsDefault": 0xea05,
		"mailB": 0xea06,
		"administrationB": 0xea07,
		"priorityDefault": 0xea08,
		"filterDefault": 0xea09,
		"administrationDefault": 0xea0a,
		"profileRound": 0xea0b,
		"policyDefault": 0xea0c,
		"shareiOS": 0xea0d,
		"statusOn": 0xea0e,
		"statusOff": 0xea0f,
		"flagCanada": 0xea10,
		"flagUK": 0xea11,
		"flagUnitedStates": 0xea12,
		"supportDefault": 0xea13,
		"restartDefault": 0xea14,
		"flagSouthAmerica": 0xea15,
		"flagAsia": 0xea16,
		"signalstrengthWired": 0xea17,
		"signalstrength4": 0xea18,
		"signalstrength0": 0xea19,
		"signalstrength3": 0xea1a,
		"signalstrength2": 0xea1b,
		"signalstrength1": 0xea1c,
		"devicesDefault": 0xea1d,
		"nodesDefault": 0xea1e,
		"uploadDefault": 0xea1f,
		"downloadDefault": 0xea20,
		"disableRound": 0xea21,
		"healthDefault": 0xea22,
		"settingsDefault": 0xea23,
		"homeDefault": 0xea24,
		"checkDefault": 0xea25,
		"checkRound": 0xea26,
		"helpRound": 0xea27,
		"arrowDown": 0xea28,
		"shieldDefault": 0xea29,
		"chevronLeft": 0xea2a,
		"chevronRight": 0xea2b,
		"chevronUp": 0xea2c,
		"chevronDown": 0xea2d,
		"profileDefault": 0xea2e,
		"crossDefault": 0xea2f,
		"addDefault": 0xea30,
		"bellDefault": 0xea31,
		"showDefault": 0xea32,
		"bellB": 0xea33,
		"wifiDefault": 0xea34,
		"hideDefault": 0xea35,
		"refreshDefault": 0xea36,
		"arrowRight": 0xea37,
		"moreHorizontal": 0xea38,
		"searchDefault": 0xea39,
		"arrowLeft": 0xea3a,
		"clockRound": 0xea3b,
		"editDefault": 0xea3c,
		"arrowUp": 0xea3d,
		"infoRound": 0xea3e,
		"securityDefault": 0xea3f,
		"moreVertical": 0xea40,
		"grabberDefault": 0xea41,
		"crossRound": 0xea42,
		"stopRound": 0xea43,
		"radioOff": 0xea44,
		"circleOn": 0xea45,
		"shareDefault": 0xea46,
		"bugDefault": 0xea47,
		"dangerDefault": 0xea48,
		"botDefault": 0xea49,
		"playRound": 0xea4a,
		"pauseRound": 0xea4b,
		"ethernetDefault": 0xea4c,
		"signalstrengthWired2": 0xea4d};
  
  class LinksysIconsCharactersData extends Equatable {
    static const fontFamily = LinksysIcons;
    
    const LinksysIconsCharactersData({
      required this.calendarDefault,
		required this.optionsDefault,
		required this.copyDefault,
		required this.qrcodeDefault,
		required this.smsDefault,
		required this.mailB,
		required this.administrationB,
		required this.priorityDefault,
		required this.filterDefault,
		required this.administrationDefault,
		required this.profileRound,
		required this.policyDefault,
		required this.shareiOS,
		required this.statusOn,
		required this.statusOff,
		required this.flagCanada,
		required this.flagUK,
		required this.flagUnitedStates,
		required this.supportDefault,
		required this.restartDefault,
		required this.flagSouthAmerica,
		required this.flagAsia,
		required this.signalstrengthWired,
		required this.signalstrength4,
		required this.signalstrength0,
		required this.signalstrength3,
		required this.signalstrength2,
		required this.signalstrength1,
		required this.devicesDefault,
		required this.nodesDefault,
		required this.uploadDefault,
		required this.downloadDefault,
		required this.disableRound,
		required this.healthDefault,
		required this.settingsDefault,
		required this.homeDefault,
		required this.checkDefault,
		required this.checkRound,
		required this.helpRound,
		required this.arrowDown,
		required this.shieldDefault,
		required this.chevronLeft,
		required this.chevronRight,
		required this.chevronUp,
		required this.chevronDown,
		required this.profileDefault,
		required this.crossDefault,
		required this.addDefault,
		required this.bellDefault,
		required this.showDefault,
		required this.bellB,
		required this.wifiDefault,
		required this.hideDefault,
		required this.refreshDefault,
		required this.arrowRight,
		required this.moreHorizontal,
		required this.searchDefault,
		required this.arrowLeft,
		required this.clockRound,
		required this.editDefault,
		required this.arrowUp,
		required this.infoRound,
		required this.securityDefault,
		required this.moreVertical,
		required this.grabberDefault,
		required this.crossRound,
		required this.stopRound,
		required this.radioOff,
		required this.circleOn,
		required this.shareDefault,
		required this.bugDefault,
		required this.dangerDefault,
		required this.botDefault,
		required this.playRound,
		required this.pauseRound,
		required this.ethernetDefault,
		required this.signalstrengthWired2
    });

    factory LinksysIconsCharactersData.regular() => LinksysIconsCharactersData(
      calendarDefault : IconData(jsonLinksysIcons['calendarDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		optionsDefault : IconData(jsonLinksysIcons['optionsDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		copyDefault : IconData(jsonLinksysIcons['copyDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		qrcodeDefault : IconData(jsonLinksysIcons['qrcodeDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		smsDefault : IconData(jsonLinksysIcons['smsDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		mailB : IconData(jsonLinksysIcons['mailB']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		administrationB : IconData(jsonLinksysIcons['administrationB']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		priorityDefault : IconData(jsonLinksysIcons['priorityDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		filterDefault : IconData(jsonLinksysIcons['filterDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		administrationDefault : IconData(jsonLinksysIcons['administrationDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		profileRound : IconData(jsonLinksysIcons['profileRound']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		policyDefault : IconData(jsonLinksysIcons['policyDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		shareiOS : IconData(jsonLinksysIcons['shareiOS']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		statusOn : IconData(jsonLinksysIcons['statusOn']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		statusOff : IconData(jsonLinksysIcons['statusOff']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		flagCanada : IconData(jsonLinksysIcons['flagCanada']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		flagUK : IconData(jsonLinksysIcons['flagUK']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		flagUnitedStates : IconData(jsonLinksysIcons['flagUnitedStates']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		supportDefault : IconData(jsonLinksysIcons['supportDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		restartDefault : IconData(jsonLinksysIcons['restartDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		flagSouthAmerica : IconData(jsonLinksysIcons['flagSouthAmerica']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		flagAsia : IconData(jsonLinksysIcons['flagAsia']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		signalstrengthWired : IconData(jsonLinksysIcons['signalstrengthWired']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		signalstrength4 : IconData(jsonLinksysIcons['signalstrength4']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		signalstrength0 : IconData(jsonLinksysIcons['signalstrength0']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		signalstrength3 : IconData(jsonLinksysIcons['signalstrength3']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		signalstrength2 : IconData(jsonLinksysIcons['signalstrength2']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		signalstrength1 : IconData(jsonLinksysIcons['signalstrength1']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		devicesDefault : IconData(jsonLinksysIcons['devicesDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		nodesDefault : IconData(jsonLinksysIcons['nodesDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		uploadDefault : IconData(jsonLinksysIcons['uploadDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		downloadDefault : IconData(jsonLinksysIcons['downloadDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		disableRound : IconData(jsonLinksysIcons['disableRound']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		healthDefault : IconData(jsonLinksysIcons['healthDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		settingsDefault : IconData(jsonLinksysIcons['settingsDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		homeDefault : IconData(jsonLinksysIcons['homeDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		checkDefault : IconData(jsonLinksysIcons['checkDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		checkRound : IconData(jsonLinksysIcons['checkRound']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		helpRound : IconData(jsonLinksysIcons['helpRound']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		arrowDown : IconData(jsonLinksysIcons['arrowDown']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		shieldDefault : IconData(jsonLinksysIcons['shieldDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		chevronLeft : IconData(jsonLinksysIcons['chevronLeft']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		chevronRight : IconData(jsonLinksysIcons['chevronRight']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		chevronUp : IconData(jsonLinksysIcons['chevronUp']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		chevronDown : IconData(jsonLinksysIcons['chevronDown']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		profileDefault : IconData(jsonLinksysIcons['profileDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		crossDefault : IconData(jsonLinksysIcons['crossDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		addDefault : IconData(jsonLinksysIcons['addDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		bellDefault : IconData(jsonLinksysIcons['bellDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		showDefault : IconData(jsonLinksysIcons['showDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		bellB : IconData(jsonLinksysIcons['bellB']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		wifiDefault : IconData(jsonLinksysIcons['wifiDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		hideDefault : IconData(jsonLinksysIcons['hideDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		refreshDefault : IconData(jsonLinksysIcons['refreshDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		arrowRight : IconData(jsonLinksysIcons['arrowRight']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		moreHorizontal : IconData(jsonLinksysIcons['moreHorizontal']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		searchDefault : IconData(jsonLinksysIcons['searchDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		arrowLeft : IconData(jsonLinksysIcons['arrowLeft']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		clockRound : IconData(jsonLinksysIcons['clockRound']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		editDefault : IconData(jsonLinksysIcons['editDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		arrowUp : IconData(jsonLinksysIcons['arrowUp']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		infoRound : IconData(jsonLinksysIcons['infoRound']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		securityDefault : IconData(jsonLinksysIcons['securityDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		moreVertical : IconData(jsonLinksysIcons['moreVertical']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		grabberDefault : IconData(jsonLinksysIcons['grabberDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		crossRound : IconData(jsonLinksysIcons['crossRound']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		stopRound : IconData(jsonLinksysIcons['stopRound']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		radioOff : IconData(jsonLinksysIcons['radioOff']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		circleOn : IconData(jsonLinksysIcons['circleOn']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		shareDefault : IconData(jsonLinksysIcons['shareDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		bugDefault : IconData(jsonLinksysIcons['bugDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		dangerDefault : IconData(jsonLinksysIcons['dangerDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		botDefault : IconData(jsonLinksysIcons['botDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		playRound : IconData(jsonLinksysIcons['playRound']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		pauseRound : IconData(jsonLinksysIcons['pauseRound']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		ethernetDefault : IconData(jsonLinksysIcons['ethernetDefault']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core'),
		signalstrengthWired2 : IconData(jsonLinksysIcons['signalstrengthWired2']!, fontFamily: 'LinksysIcons', fontPackage: 'linksys_core')
    );

    final IconData calendarDefault;
		final IconData optionsDefault;
		final IconData copyDefault;
		final IconData qrcodeDefault;
		final IconData smsDefault;
		final IconData mailB;
		final IconData administrationB;
		final IconData priorityDefault;
		final IconData filterDefault;
		final IconData administrationDefault;
		final IconData profileRound;
		final IconData policyDefault;
		final IconData shareiOS;
		final IconData statusOn;
		final IconData statusOff;
		final IconData flagCanada;
		final IconData flagUK;
		final IconData flagUnitedStates;
		final IconData supportDefault;
		final IconData restartDefault;
		final IconData flagSouthAmerica;
		final IconData flagAsia;
		final IconData signalstrengthWired;
		final IconData signalstrength4;
		final IconData signalstrength0;
		final IconData signalstrength3;
		final IconData signalstrength2;
		final IconData signalstrength1;
		final IconData devicesDefault;
		final IconData nodesDefault;
		final IconData uploadDefault;
		final IconData downloadDefault;
		final IconData disableRound;
		final IconData healthDefault;
		final IconData settingsDefault;
		final IconData homeDefault;
		final IconData checkDefault;
		final IconData checkRound;
		final IconData helpRound;
		final IconData arrowDown;
		final IconData shieldDefault;
		final IconData chevronLeft;
		final IconData chevronRight;
		final IconData chevronUp;
		final IconData chevronDown;
		final IconData profileDefault;
		final IconData crossDefault;
		final IconData addDefault;
		final IconData bellDefault;
		final IconData showDefault;
		final IconData bellB;
		final IconData wifiDefault;
		final IconData hideDefault;
		final IconData refreshDefault;
		final IconData arrowRight;
		final IconData moreHorizontal;
		final IconData searchDefault;
		final IconData arrowLeft;
		final IconData clockRound;
		final IconData editDefault;
		final IconData arrowUp;
		final IconData infoRound;
		final IconData securityDefault;
		final IconData moreVertical;
		final IconData grabberDefault;
		final IconData crossRound;
		final IconData stopRound;
		final IconData radioOff;
		final IconData circleOn;
		final IconData shareDefault;
		final IconData bugDefault;
		final IconData dangerDefault;
		final IconData botDefault;
		final IconData playRound;
		final IconData pauseRound;
		final IconData ethernetDefault;
		final IconData signalstrengthWired2;
    
    @override
    List<Named<IconData>?> get props => [
        calendarDefault.named('calendarDefault'),
		optionsDefault.named('optionsDefault'),
		copyDefault.named('copyDefault'),
		qrcodeDefault.named('qrcodeDefault'),
		smsDefault.named('smsDefault'),
		mailB.named('mailB'),
		administrationB.named('administrationB'),
		priorityDefault.named('priorityDefault'),
		filterDefault.named('filterDefault'),
		administrationDefault.named('administrationDefault'),
		profileRound.named('profileRound'),
		policyDefault.named('policyDefault'),
		shareiOS.named('shareiOS'),
		statusOn.named('statusOn'),
		statusOff.named('statusOff'),
		flagCanada.named('flagCanada'),
		flagUK.named('flagUK'),
		flagUnitedStates.named('flagUnitedStates'),
		supportDefault.named('supportDefault'),
		restartDefault.named('restartDefault'),
		flagSouthAmerica.named('flagSouthAmerica'),
		flagAsia.named('flagAsia'),
		signalstrengthWired.named('signalstrengthWired'),
		signalstrength4.named('signalstrength4'),
		signalstrength0.named('signalstrength0'),
		signalstrength3.named('signalstrength3'),
		signalstrength2.named('signalstrength2'),
		signalstrength1.named('signalstrength1'),
		devicesDefault.named('devicesDefault'),
		nodesDefault.named('nodesDefault'),
		uploadDefault.named('uploadDefault'),
		downloadDefault.named('downloadDefault'),
		disableRound.named('disableRound'),
		healthDefault.named('healthDefault'),
		settingsDefault.named('settingsDefault'),
		homeDefault.named('homeDefault'),
		checkDefault.named('checkDefault'),
		checkRound.named('checkRound'),
		helpRound.named('helpRound'),
		arrowDown.named('arrowDown'),
		shieldDefault.named('shieldDefault'),
		chevronLeft.named('chevronLeft'),
		chevronRight.named('chevronRight'),
		chevronUp.named('chevronUp'),
		chevronDown.named('chevronDown'),
		profileDefault.named('profileDefault'),
		crossDefault.named('crossDefault'),
		addDefault.named('addDefault'),
		bellDefault.named('bellDefault'),
		showDefault.named('showDefault'),
		bellB.named('bellB'),
		wifiDefault.named('wifiDefault'),
		hideDefault.named('hideDefault'),
		refreshDefault.named('refreshDefault'),
		arrowRight.named('arrowRight'),
		moreHorizontal.named('moreHorizontal'),
		searchDefault.named('searchDefault'),
		arrowLeft.named('arrowLeft'),
		clockRound.named('clockRound'),
		editDefault.named('editDefault'),
		arrowUp.named('arrowUp'),
		infoRound.named('infoRound'),
		securityDefault.named('securityDefault'),
		moreVertical.named('moreVertical'),
		grabberDefault.named('grabberDefault'),
		crossRound.named('crossRound'),
		stopRound.named('stopRound'),
		radioOff.named('radioOff'),
		circleOn.named('circleOn'),
		shareDefault.named('shareDefault'),
		bugDefault.named('bugDefault'),
		dangerDefault.named('dangerDefault'),
		botDefault.named('botDefault'),
		playRound.named('playRound'),
		pauseRound.named('pauseRound'),
		ethernetDefault.named('ethernetDefault'),
		signalstrengthWired2.named('signalstrengthWired2')
      ];
  }
  