/// The page coverage roster (#1382) — the record of which page views the gate
/// has swept, which are queued, and which are excluded.
///
/// ## What this exists to say that nothing else could
///
/// `test/fixtures/overflow_baselines/page.tsv` is a coverage register, but it
/// holds only *what was measured*: a page never onboarded appears nowhere in it,
/// so **"not yet onboarded" and "does not exist" read identically**. That is the
/// mirror of the risk the lane split guards. #1371 guards "a page that ran
/// yesterday and not today must not read as a page that was fixed"; nothing
/// guarded "a page never onboarded reads exactly like a page with no debt" — and
/// under that gap a page view added to the app after the epic closes would escape
/// the gate silently and permanently.
///
/// `page_surface_family_test.dart:60` pins `['dhcp', 'wifi_settings']` exactly,
/// which is a *change* guard — adding a case forces a deliberate edit — and not a
/// progress record. A queue posted as an issue comment rots and is not readable
/// from the repo. So the record is a committed file, and [PageRoster] is what
/// makes it checkable rather than decorative.
///
/// ## The discovery rule is load-bearing, and three spellings give three answers
///
/// [discoverPageViews] implements exactly one of them: **a file named
/// `*_view.dart` sitting directly inside a `views/` directory, at any depth under
/// `lib/page/`.** Measured on `6f8ce5ed`, and re-measured for this file:
///
/// | Spelling | Count | Verdict |
/// |---|---:|---|
/// | `lib/page/*/views/*_view.dart` (one level) | 44 | **too narrow** — misses `lib/page/login/auto_parent/views/auto_parent_first_login_view.dart` |
/// | directly inside a `views/` dir, any depth | **45** | what this file does |
/// | `find -path '*/views/*_view.dart'` | 49 | **too wide** — `*` crosses `/` in `find` |
///
/// The four false positives are all in `lib/page/unified_diagnostics/views/widgets/`:
/// `diagnostic_start_view`, `diagnostic_running_view`, `diagnostic_results_view`,
/// `diagnostic_manual_tools_view`. They are composed widgets, not pages — none of
/// the four classes appears anywhere under `lib/route/` — so they must **not** get
/// roster rows. Demanding rows for them would make the roster claim 49 pages exist
/// and permanently block "45 of 45".
///
/// Two things keep the rule honest rather than one. The walk below cannot be
/// mis-spelled the way a glob string can — the parent directory's name is compared
/// to `views` outright, so `views/widgets/` fails it structurally — and
/// [kPageViewCount] is pinned in the oracle on top of that, so a change to the walk
/// cannot silently widen or narrow the roster's obligation either.
///
/// ## Why it is a walk and not a `Glob`
///
/// `package:glob` is in `pubspec.lock` only as a transitive dependency. Importing
/// it here would make this gate depend on something no `pubspec.yaml` line asks
/// for, and it would also reintroduce the pattern-spelling question the walk
/// removes: `lib/page/**/views/*_view.dart` gives the right 45 under `Glob` and the
/// wrong 49 under `find -path`, which is precisely the trap worth not being one
/// misreading away from.
library;

import 'dart:io';

/// Where the committed roster lives, relative to the app root that `flutter test`
/// runs in — the same convention as [kKnownOverflowsFixturePath] in `ratchet.dart`.
///
/// Deliberately **not** inside `test/fixtures/overflow_baselines/`. That directory
/// is a measurement dataset regenerated by `tool/overflow_baseline.sh` and diffed
/// byte-for-byte; the roster is hand-edited and holds no measurements of its own
/// beyond the two figures it cites. A hand-edited file in a generated directory is
/// one `render` away from being clobbered.
const String kPageRosterFixturePath = 'test/fixtures/page_roster.tsv';

/// The directory the discovery rule walks.
const String kPageViewRoot = 'lib/page';

/// How many page views the rule finds today.
///
/// Pinned rather than derived so a change to [discoverPageViews] fails loudly
/// instead of quietly redefining what "45 of 45" means. Moving this number is a
/// deliberate act: either the app gained a page (add its roster row) or the rule
/// changed (say why, in the oracle's reason string).
const int kPageViewCount = 45;

/// The marker for a column with no value, spelled as the overflow baselines spell
/// it (`page.tsv` writes `-` for every absent `px`, `side`, `site` and `widget`).
///
/// #1382's AC asks for `ms/cell` to be *empty* on every queued row, and the value
/// this parses to is exactly that — `null`, meaning **not measured**, which is what
/// the AC protects: an interpolated number here would be a fabricated measurement
/// in the epic's own record. What is rejected is the *literal* empty field, because
/// a trailing tab is invisible in a diff and any editor or pre-commit hook that
/// strips trailing whitespace silently turns a three-column row into a two-column
/// one. `-` is a value that survives being looked at.
const String kNotMeasured = '-';

/// The header key that restates the row count inside the file.
const String _pagesHeaderKey = 'pages';

/// A roster the reader refuses to read.
///
/// Separate from [FormatException] for the reason `ratchet.dart` gives about its
/// own exception: a caller (and a test) can tell "the roster is malformed" apart
/// from any other parse failure in the same run.
class PageRosterFormatException implements Exception {
  PageRosterFormatException(this.message);

  final String message;

  @override
  String toString() => 'PageRosterFormatException: $message';
}

/// What the gate has done about a page.
enum PageRosterDisposition {
  /// A sweep declares this page and it is at zero. Carries a measured ms/cell.
  swept('swept'),

  /// Not onboarded yet. `ms/cell` is absent, because nothing measured it.
  queued('queued'),

  /// Deliberately out of the gate, with a written reason. A **valid** disposition
  /// from day one with nothing using it: the five candidates
  /// (`usp_sliver_dashboard_view`, `usp_dashboard_view`, `usp_test_console_view`,
  /// `router_assistant_view`, `pnp_complete_view`) get written verdicts in their
  /// own waves, and #1382 deliberately decides none of them.
  excluded('excluded');

  const PageRosterDisposition(this.token);

  /// How the disposition is spelled in the file's second column.
  final String token;
}

/// One row: a page view, what the gate has done about it, and what a cell of it
/// costs if anything has measured one.
class PageRosterRow {
  PageRosterRow({
    required this.path,
    required this.disposition,
    required this.msPerCell,
    this.exclusionReason,
    required this.lineNumber,
  });

  /// Repo-relative, posix-separated, e.g. `lib/page/dhcp/views/usp_dhcp_detail_view.dart`.
  final String path;

  final PageRosterDisposition disposition;

  /// Measured milliseconds per swept cell, or **null** for "not measured".
  ///
  /// Null is the only honest value for a queued page and the parser enforces that
  /// in both directions: a queued or excluded row may not carry a number, and a
  /// `swept` row may not omit one. A page cannot be swept without a run having
  /// happened, and §11.2's inverted bracket — the page picked as the cheap end
  /// costs 1.5× the one picked as expensive — is the argument that the number
  /// cannot be inferred from the page's shape and so has to be recorded per page.
  final double? msPerCell;

  /// Why this page is out of the gate. Non-null exactly when [disposition] is
  /// [PageRosterDisposition.excluded].
  final String? exclusionReason;

  /// 1-based line in the fixture, so a rejection can name where to look.
  final int lineNumber;

  // No `fileName` getter, on purpose. An earlier draft had one and called it "the
  // join key against a swept case's widget type", which is the bug
  // [pageViewPathsDeclaring] documents: the file name is neither the join key nor
  // an identity here, because nothing stops two features from each holding a
  // `views/x_view.dart`. [path] is the identity everywhere it matters, and a map
  // keyed on the name would silently keep whichever row came last.

  /// How this row is written back out, tabs and all.
  String get line {
    final token = disposition == PageRosterDisposition.excluded
        ? '${disposition.token}:$exclusionReason'
        : disposition.token;
    final ms = msPerCell == null ? kNotMeasured : msPerCell!.toStringAsFixed(1);
    return '$path\t$token\t$ms';
  }
}

/// The parsed roster.
class PageRoster {
  PageRoster._(this.rows, this.source);

  /// Every row, in file order — which the parser also requires to be path order.
  final List<PageRosterRow> rows;

  /// Where this roster was read from, for messages.
  final String source;

  /// Read the committed roster.
  ///
  /// A missing file is a [PageRosterFormatException] and not an empty roster, for
  /// the reason `ratchet.dart`'s header states in full: reading an unreadable
  /// record as "nothing to say" is how a guard becomes invisible. An absent roster
  /// would make every page look unrecorded, which is loud — but an absent roster
  /// read as *empty* would make the ⟺ assertion vacuous in one direction, and the
  /// gate has already been burned twice by a pass-shaped result for an unrun guard.
  factory PageRoster.fromFixture([String path = kPageRosterFixturePath]) {
    final file = File(path);
    if (!file.existsSync()) {
      throw PageRosterFormatException(
        '$path does not exist. The roster is the epic\'s coverage record; if it '
        'has been moved, move kPageRosterFixturePath with it.',
      );
    }
    return PageRoster.parse(file.readAsStringSync(), source: path);
  }

  /// Parse roster text.
  ///
  /// Every rejection below is a way the record could claim something untrue while
  /// looking well-formed, which is the only failure mode a coverage record has.
  factory PageRoster.parse(String text, {String source = '<memory>'}) {
    final rows = <PageRosterRow>[];
    final headers = <String, String>{};
    final lines = text.split('\n');

    for (var i = 0; i < lines.length; i++) {
      final raw = lines[i];
      final lineNumber = i + 1;
      if (raw.trim().isEmpty) continue;
      if (raw.startsWith('#')) {
        final body = raw.substring(1).trim();
        final space = body.indexOf(' ');
        if (space > 0) {
          headers[body.substring(0, space)] = body.substring(space + 1);
        }
        continue;
      }
      rows.add(_parseRow(raw, lineNumber, source));
    }

    _rejectDuplicates(rows, source);
    _rejectUnsorted(rows, source);
    _rejectStaleHeader(headers, rows, source);

    return PageRoster._(List.unmodifiable(rows), source);
  }

  static PageRosterRow _parseRow(String raw, int lineNumber, String source) {
    final fields = raw.split('\t');
    if (fields.length != 3) {
      throw PageRosterFormatException(
        '$source:$lineNumber has ${fields.length} tab-separated fields, not 3. '
        'A row is `path<TAB>disposition<TAB>ms_per_cell`; write `$kNotMeasured` '
        'for a page nothing has measured rather than leaving the field empty.',
      );
    }

    final path = fields[0];
    if (!isPageViewPath(path)) {
      throw PageRosterFormatException(
        '$source:$lineNumber names `$path`, which is not a page view under this '
        'roster\'s rule: a file named `*_view.dart` directly inside a `views/` '
        'directory under `$kPageViewRoot/`. A row for a composed widget one level '
        'deeper — `views/widgets/diagnostic_start_view.dart` and its three '
        'siblings are the real cases — would make the roster claim more pages '
        'exist than do, and no count of them could ever reach 45 of 45.',
      );
    }

    final token = fields[1];
    final PageRosterDisposition disposition;
    String? reason;
    if (token.startsWith('${PageRosterDisposition.excluded.token}:')) {
      disposition = PageRosterDisposition.excluded;
      reason = token.substring(PageRosterDisposition.excluded.token.length + 1);
      if (reason.trim().isEmpty) {
        throw PageRosterFormatException(
          '$source:$lineNumber excludes `$path` with no reason after the colon. '
          'An exclusion without a written reason is indistinguishable from a '
          'page someone forgot, which is the state this roster exists to end.',
        );
      }
    } else {
      final match = PageRosterDisposition.values.where(
          (d) => d.token == token && d != PageRosterDisposition.excluded);
      if (match.isEmpty) {
        throw PageRosterFormatException(
          '$source:$lineNumber gives `$path` the disposition `$token`, which is '
          'not one of `${PageRosterDisposition.swept.token}`, '
          '`${PageRosterDisposition.queued.token}` or '
          '`${PageRosterDisposition.excluded.token}:<reason>`.',
        );
      }
      disposition = match.single;
    }

    final msField = fields[2];
    double? msPerCell;
    if (msField != kNotMeasured) {
      msPerCell = double.tryParse(msField);
      if (msPerCell == null) {
        throw PageRosterFormatException(
          '$source:$lineNumber gives `$path` an ms/cell of `$msField`, which is '
          'neither a number nor `$kNotMeasured`.',
        );
      }
    }

    if (disposition == PageRosterDisposition.swept && msPerCell == null) {
      throw PageRosterFormatException(
        '$source:$lineNumber marks `$path` swept with no ms/cell. A page cannot '
        'be swept without a run having happened, and §11.2\'s bracket inverted — '
        'the page picked as the cheap end costs 1.5x the one picked as expensive '
        '— so the cost cannot be inferred from the page and has to be recorded.',
      );
    }
    if (disposition != PageRosterDisposition.swept && msPerCell != null) {
      throw PageRosterFormatException(
        '$source:$lineNumber gives `$path` an ms/cell of $msPerCell while its '
        'disposition is `$token`. Nothing has swept this page, so that number '
        'was not measured — and an interpolated figure in the epic\'s own record '
        'is a fabricated measurement.',
      );
    }

    return PageRosterRow(
      path: path,
      disposition: disposition,
      msPerCell: msPerCell,
      exclusionReason: reason,
      lineNumber: lineNumber,
    );
  }

  static void _rejectDuplicates(List<PageRosterRow> rows, String source) {
    final seen = <String, int>{};
    for (final row in rows) {
      final first = seen[row.path];
      if (first != null) {
        throw PageRosterFormatException(
          '$source:${row.lineNumber} repeats `${row.path}`, already on line '
          '$first. Two rows for one page are two dispositions for one page, and '
          'whichever the reader picked would be arbitrary.',
        );
      }
      seen[row.path] = row.lineNumber;
    }
  }

  static void _rejectUnsorted(List<PageRosterRow> rows, String source) {
    for (var i = 1; i < rows.length; i++) {
      if (rows[i].path.compareTo(rows[i - 1].path) <= 0) {
        throw PageRosterFormatException(
          '$source:${rows[i].lineNumber} — `${rows[i].path}` sorts before '
          '`${rows[i - 1].path}`. Path order is what keeps adding a page a '
          'one-line diff and keeps two waves editing this file from colliding '
          'on the same line.',
        );
      }
    }
  }

  static void _rejectStaleHeader(
    Map<String, String> headers,
    List<PageRosterRow> rows,
    String source,
  ) {
    final declared = headers[_pagesHeaderKey];
    if (declared == null) {
      throw PageRosterFormatException(
        '$source has no `# $_pagesHeaderKey <n>` header. The count is in the file '
        'so the file says how much it claims to cover without being parsed.',
      );
    }
    if (int.tryParse(declared.trim()) != rows.length) {
      throw PageRosterFormatException(
        '$source declares `# $_pagesHeaderKey $declared` and holds '
        '${rows.length} rows. A record whose own header disagrees with it is the '
        'shape of every stale count in this epic.',
      );
    }
  }

  Iterable<PageRosterRow> withDisposition(PageRosterDisposition d) =>
      rows.where((r) => r.disposition == d);

  /// Every path the roster records.
  Set<String> get paths => rows.map((r) => r.path).toSet();

  /// Paths of the rows marked swept — the left side of the ⟺ assertion.
  Set<String> get sweptPaths =>
      withDisposition(PageRosterDisposition.swept).map((r) => r.path).toSet();

  /// **Assertion 1.** Discovered page views with no roster row.
  ///
  /// Non-empty means a page view exists that the coverage record has never heard
  /// of — the escape this whole file exists to close.
  List<String> unrecordedPages(Iterable<String> discovered) =>
      discovered.where((p) => !paths.contains(p)).toList()..sort();

  /// The other half of assertion 1: rows for pages the rule does not find.
  ///
  /// Distinct from [phantomRows] — a file can exist and still fall outside the
  /// rule — though the parser's shape check makes that hard to reach.
  List<String> undiscoveredRows(Iterable<String> discovered) {
    final found = discovered.toSet();
    return rows.map((r) => r.path).where((p) => !found.contains(p)).toList()
      ..sort();
  }

  /// **Assertion 2.** Rows naming a file that is not on disk.
  ///
  /// A deleted or renamed view otherwise leaves a row claiming coverage of
  /// nothing — and a `swept` row claiming coverage of nothing is worse than a
  /// missing row, because it counts toward "45 of 45".
  List<String> phantomRows() =>
      rows.map((r) => r.path).where((p) => !File(p).existsSync()).toList()
        ..sort();
}

/// Does [path] satisfy the discovery rule?
///
/// Kept as a predicate rather than folded into the walk so the parser can hold
/// rows to the same rule the walk applies, from the same line of code.
bool isPageViewPath(String path) {
  final normalized = path.replaceAll('\\', '/');
  if (!normalized.startsWith('$kPageViewRoot/')) return false;
  if (!normalized.endsWith('_view.dart')) return false;
  final segments = normalized.split('/');
  // `[length - 1]` is the file; its parent directory must be `views` itself, not
  // merely have a `views` somewhere above it. This is the whole difference between
  // 45 and `find`'s 49.
  return segments.length >= 3 && segments[segments.length - 2] == 'views';
}

/// Every page view under the rule, in path order.
///
/// One directory walk, no pumping — which is why this oracle's cost does not
/// depend on whatever #1371 decides about where the page cells run.
List<String> discoverPageViews({String root = kPageViewRoot}) {
  final dir = Directory(root);
  if (!dir.existsSync()) {
    throw PageRosterFormatException(
      '$root does not exist, so this ran somewhere other than the app root. '
      'Every path in this gate is relative to the directory `flutter test` runs '
      'in; an empty result here would read as "the app has no pages".',
    );
  }
  final found = <String>[];
  for (final entity in dir.listSync(recursive: true, followLinks: false)) {
    if (entity is! File) continue;
    final path = entity.path.replaceAll('\\', '/');
    if (isPageViewPath(path)) found.add(path);
  }
  found.sort();
  return found;
}

/// Which page view file declares each of [typeNames].
///
/// This is the join between a swept `PageSurfaceCase` and its roster row. Three
/// candidate keys, and only the third is sound:
///
/// - **The case's `id`** (`dhcp`, `wifi_settings`) is a *sweep group name*, not a
///   file. `instant_setup` alone holds ten views, so id-to-directory is not a key
///   at all beyond the two pilot pages that happen to be alone in their feature.
/// - **The widget's type name, snake-cased** (`UspDhcpDetailView` →
///   `usp_dhcp_detail_view.dart`) reads like the convention and is wrong for a
///   page that already exists: `lib/page/instant_safety/views/instant_safety_view.dart`
///   declares **`UspInstantSafetyView`**, so a name-derived join would look for
///   `usp_instant_safety_view.dart` and find nothing. It would resolve to null for
///   that page and — worse — silently satisfy the ⟺ assertion in whichever
///   direction it was written as a subset check.
/// - **Where the class is actually declared**, which is what this does. It costs
///   45 small reads, no pumping, and it cannot disagree with the source.
///
/// Returns every match per name, not the first: the oracle asserts exactly one, so
/// two files declaring the same class name is a finding rather than a coin flip.
Map<String, List<String>> pageViewPathsDeclaring(
  Iterable<String> typeNames,
  Iterable<String> pageViews,
) {
  final patterns = {
    for (final name in typeNames)
      // `class Foo extends`, `class Foo<T>`, `abstract class Foo` — anchored at
      // the line start so a reference inside a doc comment or a body is not a
      // declaration, and `\b` so `UspDhcpDetailViewState` is not `UspDhcpDetailView`.
      name: RegExp('^(?:abstract |base |final |sealed )?class '
          '${RegExp.escape(name)}\\b'),
  };
  final found = {for (final name in typeNames) name: <String>[]};
  for (final path in pageViews) {
    final lines = File(path).readAsLinesSync();
    for (final entry in patterns.entries) {
      if (lines.any(entry.value.hasMatch)) found[entry.key]!.add(path);
    }
  }
  return found;
}
