import 'dart:async';

import 'package:privacy_gui/core/usp/services/bridge_request_throttler.dart';
import 'package:privacy_gui/core/usp/services/sse_operation_awaiter.dart';
import 'package:privacy_gui/core/utils/logger.dart';

/// Default reference paths covering all TR-181 network diagnostic operations.
///
/// - `Device.IP.Diagnostics.` — IPPing, TraceRoute, DownloadDiagnostics,
///   UploadDiagnostics, UDPEchoDiagnostics, ServerSelectionDiagnostics
/// - `Device.DNS.Diagnostics.` — NSLookupDiagnostics
const List<String> kNetworkDiagnosticsReferencePaths = [
  'Device.IP.Diagnostics.',
  'Device.DNS.Diagnostics.',
];

/// Typed wrapper around [SseOperationAwaiter] for TR-181 network diagnostic
/// Operate commands. Mirrors the signatures generated by `usp-codegen`
/// ([NetworkDiagnostics] in `lib/generated/network_diagnostics.g.dart`) but
/// integrates SSE `OperationComplete` waiting — codegen alone returns the
/// initial `operate` response which has no result data (BUG-006).
///
/// Two usage modes:
///
/// 1. **Ad-hoc** — call `ping(...)` / `nsLookup(...)` directly. Each call
///    creates and tears down its own subscription.
/// 2. **Scoped** — call [acquireScope] to obtain a [DiagnosticScope]; subsequent
///    operations on the scope share a single subscription. Caller MUST invoke
///    [DiagnosticScope.release] when done. Multiple holders are ref-counted.
class NetworkDiagnosticsExecutor {
  final SseOperationAwaiter _awaiter;
  final BridgeRequestThrottler? _throttler;

  /// Max wait for the throttler to drain before acquiring a fresh scope.
  /// Bounded so background SSE re-fetch storms cannot deadlock the user.
  static const _quiesceTimeout = Duration(seconds: 3);

  NetworkDiagnosticsExecutor(this._awaiter, [this._throttler]);

  /// Acquire a ref-counted shared subscription scope for batch operations.
  ///
  /// The default [referencePaths] subscribe both IP and DNS diagnostic
  /// subtrees so any of the seven Operate commands can be executed within the
  /// same scope. Each path is registered as its own bridge subscription —
  /// `addWildcardHandler` is client-side routing only and cannot make firmware
  /// emit events for unsubscribed paths.
  ///
  /// Before the very first acquire (ref-count 0 → 1) we wait — bounded by
  /// [_quiesceTimeout] — for the throttler to drain. The bridge serializes
  /// inbound requests, so issuing two subscription POSTs and the first
  /// `operate()` while dashboard GETs are still in-flight has been observed
  /// to push the operate ack past its 30s budget.
  ///
  /// Caller MUST eventually call [DiagnosticScope.release].
  Future<DiagnosticScope> acquireScope({
    List<String> referencePaths = kNetworkDiagnosticsReferencePaths,
  }) async {
    if (!_awaiter.hasSharedSubscription) {
      await _quiesceBridge();
    }
    await _awaiter.startSharedSession(referencePaths: referencePaths);
    return DiagnosticScope._(_awaiter);
  }

  Future<void> _quiesceBridge() async {
    final throttler = _throttler;
    if (throttler == null) return;
    try {
      await throttler.whenIdle().timeout(_quiesceTimeout);
    } on TimeoutException {
      logger.w('[Diagnostics] Bridge still busy after '
          '${_quiesceTimeout.inSeconds}s — proceeding anyway '
          '(active=${throttler.activeCount}, queued=${throttler.queueLength})');
    }
  }

  // ---------------------------------------------------------------------------
  // Ad-hoc operations (no scope) — one subscription per call.
  // ---------------------------------------------------------------------------

  Future<OperateResult> ping({
    required String host,
    int? numberOfRepetitions,
    Duration timeout = const Duration(seconds: 30),
  }) {
    final args = <String, String>{'Host': host};
    if (numberOfRepetitions != null) {
      args['NumberOfRepetitions'] = numberOfRepetitions.toString();
    }
    return _awaiter.execute(
      operateCommand: 'Device.IP.Diagnostics.IPPing()',
      referencePath: 'Device.IP.Diagnostics.',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> traceRoute({
    required String host,
    int? maxHopCount,
    Duration timeout = const Duration(seconds: 120),
  }) {
    final args = <String, String>{'Host': host};
    if (maxHopCount != null) {
      args['MaxHopCount'] = maxHopCount.toString();
    }
    return _awaiter.execute(
      operateCommand: 'Device.IP.Diagnostics.TraceRoute()',
      referencePath: 'Device.IP.Diagnostics.',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> nsLookup({
    required String hostName,
    String? dnsServer,
    Duration timeout = const Duration(seconds: 20),
  }) {
    final args = <String, String>{'HostName': hostName};
    if (dnsServer != null) {
      args['DNSServer'] = dnsServer;
    }
    return _awaiter.execute(
      operateCommand: 'Device.DNS.Diagnostics.NSLookupDiagnostics()',
      referencePath: 'Device.DNS.Diagnostics.',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> downloadDiagnostic({
    required String downloadUrl,
    String? ethernetPriority,
    String? dscp,
    int? numberOfConnections,
    Duration timeout = const Duration(seconds: 120),
  }) {
    final args = <String, String>{'DownloadURL': downloadUrl};
    if (ethernetPriority != null) args['EthernetPriority'] = ethernetPriority;
    if (dscp != null) args['DSCP'] = dscp;
    if (numberOfConnections != null) {
      args['NumberOfConnections'] = numberOfConnections.toString();
    }
    return _awaiter.execute(
      operateCommand: 'Device.IP.Diagnostics.DownloadDiagnostics()',
      referencePath: 'Device.IP.Diagnostics.',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> uploadDiagnostic({
    required String uploadUrl,
    int? testFileLength,
    String? ethernetPriority,
    String? dscp,
    int? numberOfConnections,
    Duration timeout = const Duration(seconds: 120),
  }) {
    final args = <String, String>{'UploadURL': uploadUrl};
    if (testFileLength != null) {
      args['TestFileLength'] = testFileLength.toString();
    }
    if (ethernetPriority != null) args['EthernetPriority'] = ethernetPriority;
    if (dscp != null) args['DSCP'] = dscp;
    if (numberOfConnections != null) {
      args['NumberOfConnections'] = numberOfConnections.toString();
    }
    return _awaiter.execute(
      operateCommand: 'Device.IP.Diagnostics.UploadDiagnostics()',
      referencePath: 'Device.IP.Diagnostics.',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> udpEcho({
    required String host,
    required int port,
    int? numberOfRepetitions,
    int? echoTimeout,
    int? dataBlockSize,
    Duration timeout = const Duration(seconds: 60),
  }) {
    final args = <String, String>{
      'Host': host,
      'Port': port.toString(),
    };
    if (numberOfRepetitions != null) {
      args['NumberOfRepetitions'] = numberOfRepetitions.toString();
    }
    if (echoTimeout != null) args['Timeout'] = echoTimeout.toString();
    if (dataBlockSize != null) {
      args['DataBlockSize'] = dataBlockSize.toString();
    }
    return _awaiter.execute(
      operateCommand: 'Device.IP.Diagnostics.UDPEchoDiagnostics()',
      referencePath: 'Device.IP.Diagnostics.',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> serverSelection({
    required String hostList,
    String? protocol,
    int? port,
    int? numberOfRepetitions,
    int? selectionTimeout,
    Duration timeout = const Duration(seconds: 60),
  }) {
    final args = <String, String>{'HostList': hostList};
    if (protocol != null) args['Protocol'] = protocol;
    if (port != null) args['Port'] = port.toString();
    if (numberOfRepetitions != null) {
      args['NumberOfRepetitions'] = numberOfRepetitions.toString();
    }
    if (selectionTimeout != null) {
      args['Timeout'] = selectionTimeout.toString();
    }
    return _awaiter.execute(
      operateCommand: 'Device.IP.Diagnostics.ServerSelectionDiagnostics()',
      referencePath: 'Device.IP.Diagnostics.',
      args: args,
      timeout: timeout,
    );
  }
}

/// A held shared-subscription session. Every operation invoked on this scope
/// reuses the underlying subscription registered when [release] is eventually
/// called the ref-count is decremented.
class DiagnosticScope {
  final SseOperationAwaiter _awaiter;
  bool _released = false;

  DiagnosticScope._(this._awaiter);

  bool get isReleased => _released;

  Future<OperateResult> ping({
    required String host,
    int? numberOfRepetitions,
    Duration timeout = const Duration(seconds: 30),
  }) {
    _ensureLive();
    final args = <String, String>{'Host': host};
    if (numberOfRepetitions != null) {
      args['NumberOfRepetitions'] = numberOfRepetitions.toString();
    }
    return _awaiter.executeInSession(
      operateCommand: 'Device.IP.Diagnostics.IPPing()',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> traceRoute({
    required String host,
    int? maxHopCount,
    Duration timeout = const Duration(seconds: 120),
  }) {
    _ensureLive();
    final args = <String, String>{'Host': host};
    if (maxHopCount != null) {
      args['MaxHopCount'] = maxHopCount.toString();
    }
    return _awaiter.executeInSession(
      operateCommand: 'Device.IP.Diagnostics.TraceRoute()',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> nsLookup({
    required String hostName,
    String? dnsServer,
    Duration timeout = const Duration(seconds: 20),
  }) {
    _ensureLive();
    final args = <String, String>{'HostName': hostName};
    if (dnsServer != null) {
      args['DNSServer'] = dnsServer;
    }
    return _awaiter.executeInSession(
      operateCommand: 'Device.DNS.Diagnostics.NSLookupDiagnostics()',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> downloadDiagnostic({
    required String downloadUrl,
    String? ethernetPriority,
    String? dscp,
    int? numberOfConnections,
    Duration timeout = const Duration(seconds: 120),
  }) {
    _ensureLive();
    final args = <String, String>{'DownloadURL': downloadUrl};
    if (ethernetPriority != null) args['EthernetPriority'] = ethernetPriority;
    if (dscp != null) args['DSCP'] = dscp;
    if (numberOfConnections != null) {
      args['NumberOfConnections'] = numberOfConnections.toString();
    }
    return _awaiter.executeInSession(
      operateCommand: 'Device.IP.Diagnostics.DownloadDiagnostics()',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> uploadDiagnostic({
    required String uploadUrl,
    int? testFileLength,
    String? ethernetPriority,
    String? dscp,
    int? numberOfConnections,
    Duration timeout = const Duration(seconds: 120),
  }) {
    _ensureLive();
    final args = <String, String>{'UploadURL': uploadUrl};
    if (testFileLength != null) {
      args['TestFileLength'] = testFileLength.toString();
    }
    if (ethernetPriority != null) args['EthernetPriority'] = ethernetPriority;
    if (dscp != null) args['DSCP'] = dscp;
    if (numberOfConnections != null) {
      args['NumberOfConnections'] = numberOfConnections.toString();
    }
    return _awaiter.executeInSession(
      operateCommand: 'Device.IP.Diagnostics.UploadDiagnostics()',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> udpEcho({
    required String host,
    required int port,
    int? numberOfRepetitions,
    int? echoTimeout,
    int? dataBlockSize,
    Duration timeout = const Duration(seconds: 60),
  }) {
    _ensureLive();
    final args = <String, String>{
      'Host': host,
      'Port': port.toString(),
    };
    if (numberOfRepetitions != null) {
      args['NumberOfRepetitions'] = numberOfRepetitions.toString();
    }
    if (echoTimeout != null) args['Timeout'] = echoTimeout.toString();
    if (dataBlockSize != null) {
      args['DataBlockSize'] = dataBlockSize.toString();
    }
    return _awaiter.executeInSession(
      operateCommand: 'Device.IP.Diagnostics.UDPEchoDiagnostics()',
      args: args,
      timeout: timeout,
    );
  }

  Future<OperateResult> serverSelection({
    required String hostList,
    String? protocol,
    int? port,
    int? numberOfRepetitions,
    int? selectionTimeout,
    Duration timeout = const Duration(seconds: 60),
  }) {
    _ensureLive();
    final args = <String, String>{'HostList': hostList};
    if (protocol != null) args['Protocol'] = protocol;
    if (port != null) args['Port'] = port.toString();
    if (numberOfRepetitions != null) {
      args['NumberOfRepetitions'] = numberOfRepetitions.toString();
    }
    if (selectionTimeout != null) {
      args['Timeout'] = selectionTimeout.toString();
    }
    return _awaiter.executeInSession(
      operateCommand: 'Device.IP.Diagnostics.ServerSelectionDiagnostics()',
      args: args,
      timeout: timeout,
    );
  }

  Future<void> release() async {
    if (_released) return;
    _released = true;
    await _awaiter.endSharedSession();
  }

  void _ensureLive() {
    if (_released) {
      throw StateError('DiagnosticScope already released');
    }
  }
}
