// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvTujhXf_EeAuXWeecLeDEw4FH9IuNzqc',
    appId: '1:110788105434:web:21200bdcd63b0be37281e3',
    messagingSenderId: '110788105434',
    projectId: 'linksys-app-flutter',
    authDomain: 'linksys-app-flutter.firebaseapp.com',
    storageBucket: 'linksys-app-flutter.appspot.com',
    measurementId: 'G-XWTREXPQW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATn7lXHrJ2_e8BEclZB7J3T9ETegRx9f4',
    appId: '1:110788105434:android:a243d83e7adcc6bb7281e3',
    messagingSenderId: '110788105434',
    projectId: 'linksys-app-flutter',
    storageBucket: 'linksys-app-flutter.appspot.com',
  );

  static const FirebaseOptions iosEE = FirebaseOptions(
    apiKey: 'AIzaSyAEG6J_AFleZcp06s5lUINsLmdoVwA90kI',
    appId: '1:110788105434:ios:c10401c8fde9b7c37281e3',
    messagingSenderId: '110788105434',
    projectId: 'linksys-app-flutter',
    storageBucket: 'linksys-app-flutter.appspot.com',
    iosClientId:
        '110788105434-h12ns2uc9nirulib0jmv84bv1ap8ev0k.apps.googleusercontent.com',
    iosBundleId: 'com.linksys.app.ios.ee',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEG6J_AFleZcp06s5lUINsLmdoVwA90kI',
    appId: '1:110788105434:ios:bac9ae53b469127f7281e3',
    messagingSenderId: '110788105434',
    projectId: 'linksys-app-flutter',
    storageBucket: 'linksys-app-flutter.appspot.com',
    iosClientId:
        '110788105434-2jp7p5sdmi448a623ur2hj77ljfe3tjt.apps.googleusercontent.com',
    iosBundleId: 'com.linksys.app.ios',
  );
}
