import 'package:privacy_gui/page/cs_diagnostic/models/diagnostic_client.dart';
import 'package:privacy_gui/page/cs_diagnostic/providers/cs_diagnostic_state.dart';

/// Provides realistic mock data for UI development and demos without a physical router.
class MockDiagnosticData {
  MockDiagnosticData._();

  /// Healthy home network: WAN up, 4-day uptime, 14 clients, low DHCP usage.
  static CsDiagnosticState healthy() {
    return CsDiagnosticState(
      loadState: DiagnosticLoadState.loaded,
      clients: _healthyClients,
      wanStatus: const {
        'wanStatus': 'Connected',
        'wanIPAddress': '73.158.42.117',
        'wanConnection': {'ipAddress': '73.158.42.117'},
        'macAddress': '00:1A:70:DE:AD:01',
      },
      routerHealth: const {'uptimeInSeconds': 345600, 'cpuLoad': 12, 'memoryLoad': 38},
      deviceInfo: const {
        'modelNumber': 'M60',
        'description': 'Linksys PINNACLE 2.0',
        'firmwareVersion': '1.0.17.26032012',
        'serialNumber': 'M60A1234567890',
      },
      dhcpLeasesCount: 14,
      dhcpPoolLimit: 150,
      radioInfo: const {
        'isBandSteeringSupported': true,
        'radios': [
          {
            'radioID': 'RADIO_2.4GHz',
            'physicalRadioID': '2.4 GHz',
            'settings': {'channel': 6, 'channelWidth': 40, 'mode': '802.11ax'},
          },
          {
            'radioID': 'RADIO_5GHz',
            'physicalRadioID': '5 GHz',
            'settings': {'channel': 149, 'channelWidth': 80, 'mode': '802.11ax'},
          },
        ],
      },
      guestNetwork: const {'isGuestNetworkEnabled': true},
      firmwareUpdate: const {
        'firmwareUpdateStatus': 'NoUpdateAvailable',
      },
    );
  }

  /// Degraded network: WAN down, recent reboot, DHCP 85% full, 5 flagged clients.
  static CsDiagnosticState degraded() {
    return CsDiagnosticState(
      loadState: DiagnosticLoadState.loaded,
      clients: _degradedClients,
      wanStatus: const {'wanStatus': 'Disconnected', 'wanIPAddress': ''},
      routerHealth: const {'uptimeInSeconds': 1200, 'cpuLoad': 78, 'memoryLoad': 85},
      deviceInfo: const {
        'modelNumber': 'M60',
        'description': 'Linksys PINNACLE 2.0',
        'firmwareVersion': '1.0.15.25112010',
        'serialNumber': 'M60A1234567890',
      },
      dhcpLeasesCount: 128,
      dhcpPoolLimit: 150,
      radioInfo: const {
        'isBandSteeringSupported': true,
        'radios': [
          {
            'radioID': 'RADIO_2.4GHz',
            'physicalRadioID': '2.4 GHz',
            'settings': {'channel': 1, 'channelWidth': 20, 'mode': '802.11ax'},
          },
          {
            'radioID': 'RADIO_5GHz',
            'physicalRadioID': '5 GHz',
            'settings': {'channel': 36, 'channelWidth': 80, 'mode': '802.11ax'},
          },
        ],
      },
      guestNetwork: const {'isGuestNetworkEnabled': false},
      firmwareUpdate: const {
        'firmwareUpdateStatus': 'UpdateAvailable',
        'availableUpdate': {'firmwareVersion': '1.0.17.26032012'},
      },
      backhaulInfo: const {
        'backhaulDevices': [
          {'deviceID': 'Node-Kitchen-A3F2', 'connectionType': 'Wireless', 'speedMbps': 450},
          {'deviceID': 'Node-Bedroom-B7C1', 'connectionType': 'Wireless', 'speedMbps': 120},
        ],
      },
    );
  }

  static const List<DiagnosticClient> _healthyClients = [
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:01',
      hostname: 'iPhone 15 Pro',
      ipAddress: '192.168.1.101',
      band: '5GHz',
      signalDecibels: -38,
      txRateMbps: 866,
      rxRateMbps: 780,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:02',
      hostname: 'MacBook Air',
      ipAddress: '192.168.1.102',
      band: '5GHz',
      signalDecibels: -42,
      txRateMbps: 1200,
      rxRateMbps: 960,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:03',
      hostname: 'Samsung TV',
      ipAddress: '192.168.1.103',
      band: '5GHz',
      signalDecibels: -52,
      txRateMbps: 433,
      rxRateMbps: 390,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:04',
      hostname: 'iPad Pro',
      ipAddress: '192.168.1.104',
      band: '5GHz',
      signalDecibels: -45,
      txRateMbps: 866,
      rxRateMbps: 720,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:05',
      hostname: 'PlayStation 5',
      ipAddress: '192.168.1.105',
      band: '5GHz',
      signalDecibels: -55,
      txRateMbps: 433,
      rxRateMbps: 400,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:06',
      hostname: 'Work Laptop',
      ipAddress: '192.168.1.106',
      band: '5GHz',
      signalDecibels: -48,
      txRateMbps: 866,
      rxRateMbps: 810,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:07',
      hostname: 'Pixel 8',
      ipAddress: '192.168.1.107',
      band: '5GHz',
      signalDecibels: -50,
      txRateMbps: 866,
      rxRateMbps: 720,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:08',
      hostname: 'Ring Doorbell',
      ipAddress: '192.168.1.108',
      band: '2.4GHz',
      signalDecibels: -68,
      txRateMbps: 72,
      rxRateMbps: 65,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:09',
      hostname: 'Nest Thermostat',
      ipAddress: '192.168.1.109',
      band: '2.4GHz',
      signalDecibels: -65,
      txRateMbps: 72,
      rxRateMbps: 60,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:0A',
      hostname: 'Echo Dot',
      ipAddress: '192.168.1.110',
      band: '2.4GHz',
      signalDecibels: -70,
      txRateMbps: 65,
      rxRateMbps: 54,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:0B',
      hostname: 'Smart Plug',
      ipAddress: '192.168.1.111',
      band: '2.4GHz',
      signalDecibels: -72,
      txRateMbps: 54,
      rxRateMbps: 48,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:0C',
      hostname: 'Baby Monitor',
      ipAddress: '192.168.1.112',
      band: '2.4GHz',
      signalDecibels: -78,
      txRateMbps: 24,
      rxRateMbps: 18,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:0D',
      hostname: 'HP Printer',
      ipAddress: '192.168.1.113',
      band: 'Wired',
      isWireless: false,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:0E',
      hostname: 'Work Desktop',
      ipAddress: '192.168.1.114',
      band: 'Wired',
      isWireless: false,
    ),
  ];

  static const List<DiagnosticClient> _degradedClients = [
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:01',
      hostname: 'iPhone 15 Pro',
      ipAddress: '192.168.1.101',
      band: '5GHz',
      signalDecibels: -55,
      txRateMbps: 433,
      rxRateMbps: 380,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:02',
      hostname: 'MacBook Air',
      ipAddress: '192.168.1.102',
      band: '5GHz',
      signalDecibels: -60,
      txRateMbps: 400,
      rxRateMbps: 350,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:03',
      hostname: 'Samsung TV',
      ipAddress: '192.168.1.103',
      band: '5GHz',
      signalDecibels: -78,
      txRateMbps: 72,
      rxRateMbps: 54,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:04',
      hostname: 'iPad Pro',
      ipAddress: '192.168.1.104',
      band: '5GHz',
      signalDecibels: -48,
      txRateMbps: 866,
      rxRateMbps: 720,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:05',
      hostname: 'Ring Doorbell',
      ipAddress: '192.168.1.105',
      band: '2.4GHz',
      signalDecibels: -82,
      txRateMbps: 11,
      rxRateMbps: 8,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:06',
      hostname: 'Nest Thermostat',
      ipAddress: '192.168.1.106',
      band: '2.4GHz',
      signalDecibels: -80,
      txRateMbps: 18,
      rxRateMbps: 12,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:07',
      hostname: 'Echo Dot',
      ipAddress: '192.168.1.107',
      band: '2.4GHz',
      signalDecibels: -85,
      txRateMbps: 6,
      rxRateMbps: 5,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:08',
      hostname: 'Baby Monitor',
      ipAddress: '192.168.1.108',
      band: '2.4GHz',
      signalDecibels: -83,
      txRateMbps: 9,
      rxRateMbps: 7,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:09',
      hostname: 'Smart Plug',
      ipAddress: '192.168.1.109',
      band: '2.4GHz',
      signalDecibels: -79,
      txRateMbps: 24,
      rxRateMbps: 18,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:0A',
      hostname: 'Work Laptop',
      ipAddress: '192.168.1.110',
      band: '5GHz',
      signalDecibels: -65,
      txRateMbps: 200,
      rxRateMbps: 180,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:0B',
      hostname: 'Pixel 8',
      ipAddress: '192.168.1.111',
      band: '5GHz',
      signalDecibels: -70,
      txRateMbps: 144,
      rxRateMbps: 120,
      isWireless: true,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:0C',
      hostname: 'HP Printer',
      ipAddress: '192.168.1.112',
      band: 'Wired',
      isWireless: false,
    ),
    DiagnosticClient(
      macAddress: 'AA:BB:CC:11:22:0D',
      hostname: 'PlayStation 5',
      ipAddress: '192.168.1.113',
      band: 'Wired',
      isWireless: false,
    ),
  ];
}
