// Mocks generated by Mockito 5.4.4 from annotations
// in privacy_gui/test/page/safe_browsing/views/localizations/safe_browsing_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/core/jnap/models/lan_settings.dart' as _i6;
import 'package:privacy_gui/page/safe_browsing/providers/safe_browsing_provider.dart'
    as _i4;
import 'package:privacy_gui/page/safe_browsing/providers/safe_browsing_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSafeBrowsingState_1 extends _i1.SmartFake
    implements _i3.SafeBrowsingState {
  _FakeSafeBrowsingState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SafeBrowsingNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSafeBrowsingNotifier extends _i2.Notifier<_i3.SafeBrowsingState> with _i1.Mock
    implements _i4.SafeBrowsingNotifier {
  @override
  _i2.NotifierProviderRef<_i3.SafeBrowsingState> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.SafeBrowsingState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.SafeBrowsingState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.SafeBrowsingState>);

  @override
  _i3.SafeBrowsingState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSafeBrowsingState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeSafeBrowsingState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.SafeBrowsingState);

  @override
  set state(_i3.SafeBrowsingState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.SafeBrowsingState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeSafeBrowsingState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeSafeBrowsingState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.SafeBrowsingState);

  @override
  _i5.Future<dynamic> fetchLANSettings({bool? fetchRemote = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLANSettings,
          [],
          {#fetchRemote: fetchRemote},
        ),
        returnValue: _i5.Future<dynamic>.value(),
        returnValueForMissingStub: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> setSafeBrowsing(_i3.SafeBrowsingType? safeBrowsingType) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSafeBrowsing,
          [safeBrowsingType],
        ),
        returnValue: _i5.Future<dynamic>.value(),
        returnValueForMissingStub: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i3.SafeBrowsingType getSafeBrowsingType(
          _i6.RouterLANSettings? lanSettings) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSafeBrowsingType,
          [lanSettings],
        ),
        returnValue: _i3.SafeBrowsingType.off,
        returnValueForMissingStub: _i3.SafeBrowsingType.off,
      ) as _i3.SafeBrowsingType);

  @override
  bool hasFortinet() => (super.noSuchMethod(
        Invocation.method(
          #hasFortinet,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool updateShouldNotify(
    _i3.SafeBrowsingState? previous,
    _i3.SafeBrowsingState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
