// Mocks generated by Mockito 5.4.5 from annotations
// in privacy_gui/test/mocks/mockito_specs/administration_settings_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/page/advanced_settings/administration/_administration.dart';
import 'package:privacy_gui/page/advanced_settings/administration/providers/administration_settings_provider.dart'
    as _i4;
import 'package:privacy_gui/page/advanced_settings/administration/providers/administration_settings_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdministrationSettingsState_1 extends _i1.SmartFake
    implements _i3.AdministrationSettingsState {
  _FakeAdministrationSettingsState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdministrationSettingsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdministrationSettingsNotifier
    extends _i2.Notifier<_i3.AdministrationSettingsState>
    with _i1.Mock
    implements _i4.AdministrationSettingsNotifier {
  @override
  _i2.NotifierProviderRef<_i3.AdministrationSettingsState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue:
            _FakeNotifierProviderRef_0<_i3.AdministrationSettingsState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.AdministrationSettingsState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.AdministrationSettingsState>);

  @override
  _i3.AdministrationSettingsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAdministrationSettingsState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeAdministrationSettingsState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AdministrationSettingsState);

  @override
  set state(_i3.AdministrationSettingsState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AdministrationSettingsState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeAdministrationSettingsState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeAdministrationSettingsState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.AdministrationSettingsState);

  @override
  _i5.Future<(_i3.AdministrationSettings?, _i3.AdministrationStatus?)>
      performFetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #performFetch,
              [],
              {
                #forceRemote: forceRemote,
                #updateStatusOnly: updateStatusOnly,
              },
            ),
            returnValue: _i5.Future<
                (
                  _i3.AdministrationSettings?,
                  _i3.AdministrationStatus?
                )>.value((null, null)),
            returnValueForMissingStub: _i5.Future<
                (
                  _i3.AdministrationSettings?,
                  _i3.AdministrationStatus?
                )>.value((null, null)),
          ) as _i5.Future<
              (_i3.AdministrationSettings?, _i3.AdministrationStatus?)>);

  @override
  _i5.Future<void> performSave() => (super.noSuchMethod(
        Invocation.method(
          #performSave,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setManagementSettings(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setManagementSettings,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUPnPEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setUPnPEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCanUsersConfigure(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setCanUsersConfigure,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCanUsersDisableWANAccess(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setCanUsersDisableWANAccess,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setALGEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setALGEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setExpressForwarding(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setExpressForwarding,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      _i3.AdministrationSettingsState?,
      _i3.AdministrationSettingsState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.AdministrationSettingsState? previous,
    _i3.AdministrationSettingsState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<_i3.AdministrationSettingsState> fetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
          {
            #forceRemote: forceRemote,
            #updateStatusOnly: updateStatusOnly,
          },
        ),
        returnValue: _i5.Future<_i3.AdministrationSettingsState>.value(
            _FakeAdministrationSettingsState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AdministrationSettingsState>.value(
                _FakeAdministrationSettingsState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
      ) as _i5.Future<_i3.AdministrationSettingsState>);

  @override
  _i5.Future<_i3.AdministrationSettingsState> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i5.Future<_i3.AdministrationSettingsState>.value(
            _FakeAdministrationSettingsState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AdministrationSettingsState>.value(
                _FakeAdministrationSettingsState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i5.Future<_i3.AdministrationSettingsState>);

  @override
  void revert() => super.noSuchMethod(
        Invocation.method(
          #revert,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isDirty() => (super.noSuchMethod(
        Invocation.method(
          #isDirty,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void markAsSaved() => super.noSuchMethod(
        Invocation.method(
          #markAsSaved,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
