// Mocks generated by Mockito 5.4.6 from annotations
// in privacy_gui/test/mocks/mockito_specs/auto_parent_first_login_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/page/login/auto_parent/providers/auto_parent_first_login_provider.dart'
    as _i4;
import 'package:privacy_gui/page/login/auto_parent/providers/auto_parent_first_login_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.AutoDisposeNotifierProviderRef<T> {
  _FakeAutoDisposeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutoParentFirstLoginState_1 extends _i1.SmartFake
    implements _i3.AutoParentFirstLoginState {
  _FakeAutoParentFirstLoginState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AutoParentFirstLoginNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutoParentFirstLoginNotifier
    extends _i2.AutoDisposeNotifier<_i3.AutoParentFirstLoginState>
    with _i1.Mock
    implements _i4.AutoParentFirstLoginNotifier {
  @override
  _i2.AutoDisposeNotifierProviderRef<_i3.AutoParentFirstLoginState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAutoDisposeNotifierProviderRef_0<
            _i3.AutoParentFirstLoginState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeAutoDisposeNotifierProviderRef_0<
            _i3.AutoParentFirstLoginState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.AutoDisposeNotifierProviderRef<_i3.AutoParentFirstLoginState>);

  @override
  _i3.AutoParentFirstLoginState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAutoParentFirstLoginState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeAutoParentFirstLoginState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AutoParentFirstLoginState);

  @override
  set state(_i3.AutoParentFirstLoginState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AutoParentFirstLoginState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeAutoParentFirstLoginState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeAutoParentFirstLoginState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.AutoParentFirstLoginState);

  @override
  _i5.Future<bool> checkAndAutoInstallFirmware() => (super.noSuchMethod(
        Invocation.method(
          #checkAndAutoInstallFirmware,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setUserAcknowledgedAutoConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserAcknowledgedAutoConfiguration,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setFirmwareUpdatePolicy() => (super.noSuchMethod(
        Invocation.method(
          #setFirmwareUpdatePolicy,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> checkInternetConnection() => (super.noSuchMethod(
        Invocation.method(
          #checkInternetConnection,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> finishFirstTimeLogin([bool? failCheck = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #finishFirstTimeLogin,
          [failCheck],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void listenSelf(
    void Function(
      _i3.AutoParentFirstLoginState?,
      _i3.AutoParentFirstLoginState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.AutoParentFirstLoginState? previous,
    _i3.AutoParentFirstLoginState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
