// Mocks generated by Mockito 5.4.5 from annotations
// in privacy_gui/test/mocks/mockito_specs/cs_diagnostic_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/page/cs_diagnostic/providers/cs_diagnostic_auth_provider.dart'
    as _i3;
import 'package:privacy_gui/page/cs_diagnostic/providers/cs_diagnostic_provider.dart'
    as _i6;
import 'package:privacy_gui/page/cs_diagnostic/providers/cs_diagnostic_state.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiagnosticAuthState_1 extends _i1.SmartFake
    implements _i3.DiagnosticAuthState {
  _FakeDiagnosticAuthState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCsDiagnosticState_2 extends _i1.SmartFake
    implements _i4.CsDiagnosticState {
  _FakeCsDiagnosticState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DiagnosticAuthNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiagnosticAuthNotifier extends _i2.Notifier<_i3.DiagnosticAuthState>
    with _i1.Mock
    implements _i3.DiagnosticAuthNotifier {
  MockDiagnosticAuthNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get mockMode =>
      (super.noSuchMethod(Invocation.getter(#mockMode), returnValue: false)
          as bool);

  @override
  set mockMode(bool? _mockMode) => super.noSuchMethod(
    Invocation.setter(#mockMode, _mockMode),
    returnValueForMissingStub: null,
  );

  @override
  _i2.NotifierProviderRef<_i3.DiagnosticAuthState> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeNotifierProviderRef_0<_i3.DiagnosticAuthState>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i2.NotifierProviderRef<_i3.DiagnosticAuthState>);

  @override
  _i3.DiagnosticAuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeDiagnosticAuthState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.DiagnosticAuthState);

  @override
  set state(_i3.DiagnosticAuthState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.DiagnosticAuthState build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeDiagnosticAuthState_1(
              this,
              Invocation.method(#build, []),
            ),
          )
          as _i3.DiagnosticAuthState);

  @override
  _i5.Future<bool> login(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [password]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void logout() => super.noSuchMethod(
    Invocation.method(#logout, []),
    returnValueForMissingStub: null,
  );

  @override
  void listenSelf(
    void Function(_i3.DiagnosticAuthState?, _i3.DiagnosticAuthState)?
    listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(
    _i3.DiagnosticAuthState? previous,
    _i3.DiagnosticAuthState? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [CsDiagnosticNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockCsDiagnosticNotifier extends _i2.Notifier<_i4.CsDiagnosticState>
    with _i1.Mock
    implements _i6.CsDiagnosticNotifier {
  MockCsDiagnosticNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get useMock =>
      (super.noSuchMethod(Invocation.getter(#useMock), returnValue: false)
          as bool);

  @override
  bool get useDegraded =>
      (super.noSuchMethod(Invocation.getter(#useDegraded), returnValue: false)
          as bool);

  @override
  _i2.NotifierProviderRef<_i4.CsDiagnosticState> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeNotifierProviderRef_0<_i4.CsDiagnosticState>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i2.NotifierProviderRef<_i4.CsDiagnosticState>);

  @override
  _i4.CsDiagnosticState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeCsDiagnosticState_2(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.CsDiagnosticState);

  @override
  set state(_i4.CsDiagnosticState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.CsDiagnosticState build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeCsDiagnosticState_2(
              this,
              Invocation.method(#build, []),
            ),
          )
          as _i4.CsDiagnosticState);

  @override
  _i5.Future<void> fetch() =>
      (super.noSuchMethod(
            Invocation.method(#fetch, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void toggleMock() => super.noSuchMethod(
    Invocation.method(#toggleMock, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleDegraded() => super.noSuchMethod(
    Invocation.method(#toggleDegraded, []),
    returnValueForMissingStub: null,
  );

  @override
  void listenSelf(
    void Function(_i4.CsDiagnosticState?, _i4.CsDiagnosticState)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(
    _i4.CsDiagnosticState? previous,
    _i4.CsDiagnosticState? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}
