// Mocks generated by Mockito 5.4.4 from annotations
// in privacy_gui/test/page/dashboard/localizations/dashboard_home_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/core/jnap/providers/dashboard_manager_state.dart'
    as _i8;
import 'package:privacy_gui/core/jnap/providers/device_manager_state.dart'
    as _i5;
import 'package:privacy_gui/page/dashboard/providers/dashboard_home_provider.dart'
    as _i7;
import 'package:privacy_gui/page/dashboard/providers/dashboard_home_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDashboardHomeState_1 extends _i1.SmartFake
    implements _i3.DashboardHomeState {
  _FakeDashboardHomeState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DashboardHomeNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardHomeNotifier extends _i2.Notifier<_i3.DashboardHomeState>
    with _i1.Mock
    implements _i7.DashboardHomeNotifier {
  @override
  _i2.NotifierProviderRef<_i3.DashboardHomeState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.DashboardHomeState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.DashboardHomeState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.DashboardHomeState>);

  @override
  _i3.DashboardHomeState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeDashboardHomeState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeDashboardHomeState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.DashboardHomeState);

  @override
  set state(_i3.DashboardHomeState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DashboardHomeState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeDashboardHomeState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDashboardHomeState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.DashboardHomeState);

  @override
  _i3.DashboardHomeState createState(
    _i8.DashboardManagerState? dashboardManagerState,
    _i5.DeviceManagerState? deviceManagerState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createState,
          [
            dashboardManagerState,
            deviceManagerState,
          ],
        ),
        returnValue: _FakeDashboardHomeState_1(
          this,
          Invocation.method(
            #createState,
            [
              dashboardManagerState,
              deviceManagerState,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeDashboardHomeState_1(
          this,
          Invocation.method(
            #createState,
            [
              dashboardManagerState,
              deviceManagerState,
            ],
          ),
        ),
      ) as _i3.DashboardHomeState);

  @override
  bool updateShouldNotify(
    _i3.DashboardHomeState? previous,
    _i3.DashboardHomeState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
