// Mocks generated by Mockito 5.4.6 from annotations
// in privacy_gui/test/mocks/mockito_specs/dashboard_manager_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/core/jnap/models/device_info.dart' as _i4;
import 'package:privacy_gui/core/jnap/providers/dashboard_manager_provider.dart'
    as _i5;
import 'package:privacy_gui/core/jnap/providers/dashboard_manager_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDashboardManagerState_1 extends _i1.SmartFake
    implements _i3.DashboardManagerState {
  _FakeDashboardManagerState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNodeDeviceInfo_2 extends _i1.SmartFake
    implements _i4.NodeDeviceInfo {
  _FakeNodeDeviceInfo_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DashboardManagerNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardManagerNotifier extends _i1.Mock
    implements _i5.DashboardManagerNotifier {
  @override
  _i2.NotifierProviderRef<_i3.DashboardManagerState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.DashboardManagerState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.DashboardManagerState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.DashboardManagerState>);

  @override
  _i3.DashboardManagerState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeDashboardManagerState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeDashboardManagerState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.DashboardManagerState);

  @override
  set state(_i3.DashboardManagerState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DashboardManagerState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeDashboardManagerState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDashboardManagerState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.DashboardManagerState);

  @override
  _i6.Future<void> saveSelectedNetwork(
    String? serialNumber,
    String? networkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSelectedNetwork,
          [
            serialNumber,
            networkId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.NodeDeviceInfo> checkRouterIsBack() => (super.noSuchMethod(
        Invocation.method(
          #checkRouterIsBack,
          [],
        ),
        returnValue: _i6.Future<_i4.NodeDeviceInfo>.value(_FakeNodeDeviceInfo_2(
          this,
          Invocation.method(
            #checkRouterIsBack,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.NodeDeviceInfo>.value(_FakeNodeDeviceInfo_2(
          this,
          Invocation.method(
            #checkRouterIsBack,
            [],
          ),
        )),
      ) as _i6.Future<_i4.NodeDeviceInfo>);

  @override
  _i6.Future<_i4.NodeDeviceInfo> checkDeviceInfo(String? serialNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkDeviceInfo,
          [serialNumber],
        ),
        returnValue: _i6.Future<_i4.NodeDeviceInfo>.value(_FakeNodeDeviceInfo_2(
          this,
          Invocation.method(
            #checkDeviceInfo,
            [serialNumber],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.NodeDeviceInfo>.value(_FakeNodeDeviceInfo_2(
          this,
          Invocation.method(
            #checkDeviceInfo,
            [serialNumber],
          ),
        )),
      ) as _i6.Future<_i4.NodeDeviceInfo>);

  @override
  void listenSelf(
    void Function(
      _i3.DashboardManagerState?,
      _i3.DashboardManagerState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.DashboardManagerState? previous,
    _i3.DashboardManagerState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
