// Mocks generated by Mockito 5.4.4 from annotations
// in privacy_gui/test/page/wifi_settings/mock_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/core/jnap/providers/device_manager_state.dart'
    as _i4;
import 'package:privacy_gui/page/devices/_devices.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeviceListState_1 extends _i1.SmartFake
    implements _i3.DeviceListState {
  _FakeDeviceListState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeviceListItem_2 extends _i1.SmartFake
    implements _i3.DeviceListItem {
  _FakeDeviceListItem_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DeviceListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceListNotifier extends _i2.Notifier<_i3.DeviceListState> with _i1.Mock
    implements _i3.DeviceListNotifier {
  @override
  _i2.NotifierProviderRef<_i3.DeviceListState> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.DeviceListState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.DeviceListState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.DeviceListState>);

  @override
  _i3.DeviceListState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeDeviceListState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeDeviceListState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.DeviceListState);

  @override
  set state(_i3.DeviceListState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DeviceListState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeDeviceListState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDeviceListState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.DeviceListState);

  @override
  _i3.DeviceListState createState(_i4.DeviceManagerState? deviceManagerState) =>
      (super.noSuchMethod(
        Invocation.method(
          #createState,
          [deviceManagerState],
        ),
        returnValue: _FakeDeviceListState_1(
          this,
          Invocation.method(
            #createState,
            [deviceManagerState],
          ),
        ),
        returnValueForMissingStub: _FakeDeviceListState_1(
          this,
          Invocation.method(
            #createState,
            [deviceManagerState],
          ),
        ),
      ) as _i3.DeviceListState);

  @override
  _i3.DeviceListItem createItem(_i4.LinksysDevice? device) =>
      (super.noSuchMethod(
        Invocation.method(
          #createItem,
          [device],
        ),
        returnValue: _FakeDeviceListItem_2(
          this,
          Invocation.method(
            #createItem,
            [device],
          ),
        ),
        returnValueForMissingStub: _FakeDeviceListItem_2(
          this,
          Invocation.method(
            #createItem,
            [device],
          ),
        ),
      ) as _i3.DeviceListItem);

  @override
  bool updateShouldNotify(
    _i3.DeviceListState? previous,
    _i3.DeviceListState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
