// Mocks generated by Mockito 5.4.5 from annotations
// in privacy_gui/test/mocks/mockito_specs/dhcp_reservations_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/core/jnap/models/lan_settings.dart' as _i6;
import 'package:privacy_gui/page/advanced_settings/local_network_settings/providers/dhcp_reservations_provider.dart'
    as _i4;
import 'package:privacy_gui/page/advanced_settings/local_network_settings/providers/dhcp_reservations_state.dart'
    as _i3;
import 'package:privacy_gui/page/instant_device/_instant_device.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDHCPReservationState_1 extends _i1.SmartFake
    implements _i3.DHCPReservationState {
  _FakeDHCPReservationState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DHCPReservationsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockDHCPReservationsNotifier extends _i2.AutoDisposeNotifier<_i3.DHCPReservationState> with _i1.Mock implements _i4.DHCPReservationsNotifier {
  @override
  set state(_i3.DHCPReservationState? newState) => super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.AutoDisposeNotifierProviderRef<_i3.DHCPReservationState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.DHCPReservationState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.DHCPReservationState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.AutoDisposeNotifierProviderRef<_i3.DHCPReservationState>);

  @override
  _i3.DHCPReservationState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeDHCPReservationState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeDHCPReservationState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.DHCPReservationState);

  @override
  _i3.DHCPReservationState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeDHCPReservationState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDHCPReservationState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.DHCPReservationState);

  @override
  bool updateShouldNotify(
    _i3.DHCPReservationState? previous,
    _i3.DHCPReservationState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<(_i3.DHCPReservationsSettings?, _i3.DHCPReservationsStatus?)>
      performFetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #performFetch,
              [],
              {
                #forceRemote: forceRemote,
                #updateStatusOnly: updateStatusOnly,
              },
            ),
            returnValue: _i5.Future<
                (
                  _i3.DHCPReservationsSettings?,
                  _i3.DHCPReservationsStatus?
                )>.value((null, null)),
            returnValueForMissingStub: _i5.Future<
                (
                  _i3.DHCPReservationsSettings?,
                  _i3.DHCPReservationsStatus?
                )>.value((null, null)),
          ) as _i5.Future<
              (_i3.DHCPReservationsSettings?, _i3.DHCPReservationsStatus?)>);

  @override
  _i5.Future<void> performSave() => (super.noSuchMethod(
        Invocation.method(
          #performSave,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setInitialReservations(List<_i6.DHCPReservation>? reservedList) =>
      super.noSuchMethod(
        Invocation.method(
          #setInitialReservations,
          [reservedList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateSettings(_i3.DHCPReservationsSettings? newSettings) =>
      super.noSuchMethod(
        Invocation.method(
          #updateSettings,
          [newSettings],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDevices([List<_i7.DeviceListItem>? deviceList = const []]) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDevices,
          [deviceList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isConflict(_i3.ReservedListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #isConflict,
          [item],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void updateReservationItem(
    _i3.ReservedListItem? editedItem,
    String? name,
    String? ip,
    String? mac,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateReservationItem,
          [
            editedItem,
            name,
            ip,
            mac,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateReservations(
    _i3.ReservedListItem? item, [
    bool? isNew = false,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #updateReservations,
          [
            item,
            isNew,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      _i3.DHCPReservationState?,
      _i3.DHCPReservationState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.DHCPReservationState> fetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
          {
            #forceRemote: forceRemote,
            #updateStatusOnly: updateStatusOnly,
          },
        ),
        returnValue: _i5.Future<_i3.DHCPReservationState>.value(
            _FakeDHCPReservationState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.DHCPReservationState>.value(
            _FakeDHCPReservationState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
      ) as _i5.Future<_i3.DHCPReservationState>);

  @override
  _i5.Future<_i3.DHCPReservationState> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i5.Future<_i3.DHCPReservationState>.value(
            _FakeDHCPReservationState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.DHCPReservationState>.value(
            _FakeDHCPReservationState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i5.Future<_i3.DHCPReservationState>);

  @override
  void revert() => super.noSuchMethod(
        Invocation.method(
          #revert,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isDirty() => (super.noSuchMethod(
        Invocation.method(
          #isDirty,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void markAsSaved() => super.noSuchMethod(
        Invocation.method(
          #markAsSaved,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
