// Mocks generated by Mockito 5.4.5 from annotations
// in privacy_gui/test/mocks/mockito_specs/dmz_setting_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:privacy_gui/core/jnap/models/dmz_settings.dart' as _i7;
import 'package:privacy_gui/page/advanced_settings/dmz/providers/dmz_settings_provider.dart'
    as _i4;
import 'package:privacy_gui/page/advanced_settings/dmz/providers/dmz_settings_state.dart'
    as _i3;
import 'package:privacy_gui/providers/empty_status.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDMZSettingsState_1 extends _i1.SmartFake
    implements _i3.DMZSettingsState {
  _FakeDMZSettingsState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DMZSettingsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockDMZSettingsNotifier extends _i2.Notifier<_i3.DMZSettingsState>
    with _i1.Mock
    implements _i4.DMZSettingsNotifier {
  @override
  String get subnetMask => (super.noSuchMethod(
        Invocation.getter(#subnetMask),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#subnetMask),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#subnetMask),
        ),
      ) as String);

  @override
  String get ipAddress => (super.noSuchMethod(
        Invocation.getter(#ipAddress),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#ipAddress),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#ipAddress),
        ),
      ) as String);

  @override
  _i2.NotifierProviderRef<_i3.DMZSettingsState> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.DMZSettingsState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.DMZSettingsState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.DMZSettingsState>);

  @override
  _i3.DMZSettingsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeDMZSettingsState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeDMZSettingsState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.DMZSettingsState);

  @override
  set state(_i3.DMZSettingsState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DMZSettingsState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeDMZSettingsState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDMZSettingsState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.DMZSettingsState);

  @override
  _i6.Future<(_i7.DMZSettings?, _i8.EmptyStatus?)> performFetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performFetch,
          [],
          {
            #forceRemote: forceRemote,
            #updateStatusOnly: updateStatusOnly,
          },
        ),
        returnValue: _i6.Future<(_i7.DMZSettings?, _i8.EmptyStatus?)>.value(
            (null, null)),
        returnValueForMissingStub:
            _i6.Future<(_i7.DMZSettings?, _i8.EmptyStatus?)>.value(
                (null, null)),
      ) as _i6.Future<(_i7.DMZSettings?, _i8.EmptyStatus?)>);

  @override
  _i6.Future<void> performSave() => (super.noSuchMethod(
        Invocation.method(
          #performSave,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setSettings(_i7.DMZSettings? settings) => super.noSuchMethod(
        Invocation.method(
          #setSettings,
          [settings],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSourceType(_i7.DMZSourceType? type) => super.noSuchMethod(
        Invocation.method(
          #setSourceType,
          [type],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDestinationType(_i7.DMZDestinationType? type) => super.noSuchMethod(
        Invocation.method(
          #setDestinationType,
          [type],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearDestinations() => super.noSuchMethod(
        Invocation.method(
          #clearDestinations,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      _i3.DMZSettingsState?,
      _i3.DMZSettingsState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.DMZSettingsState? previous,
    _i3.DMZSettingsState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<_i3.DMZSettingsState> fetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
          {
            #forceRemote: forceRemote,
            #updateStatusOnly: updateStatusOnly,
          },
        ),
        returnValue:
            _i6.Future<_i3.DMZSettingsState>.value(_FakeDMZSettingsState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.DMZSettingsState>.value(_FakeDMZSettingsState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
      ) as _i6.Future<_i3.DMZSettingsState>);

  @override
  _i6.Future<_i3.DMZSettingsState> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue:
            _i6.Future<_i3.DMZSettingsState>.value(_FakeDMZSettingsState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.DMZSettingsState>.value(_FakeDMZSettingsState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i6.Future<_i3.DMZSettingsState>);

  @override
  void revert() => super.noSuchMethod(
        Invocation.method(
          #revert,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isDirty() => (super.noSuchMethod(
        Invocation.method(
          #isDirty,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void markAsSaved() => super.noSuchMethod(
        Invocation.method(
          #markAsSaved,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
