// Mocks generated by Mockito 5.4.5 from annotations
// in privacy_gui/test/mocks/mockito_specs/instant_safety_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/page/instant_safety/providers/instant_safety_provider.dart'
    as _i4;
import 'package:privacy_gui/page/instant_safety/providers/instant_safety_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInstantSafetyState_1 extends _i1.SmartFake
    implements _i3.InstantSafetyState {
  _FakeInstantSafetyState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InstantSafetyNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockInstantSafetyNotifier extends _i2.Notifier<_i3.InstantSafetyState>
    with _i1.Mock
    implements _i4.InstantSafetyNotifier {
  @override
  _i2.NotifierProviderRef<_i3.InstantSafetyState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.InstantSafetyState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.InstantSafetyState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.InstantSafetyState>);

  @override
  _i3.InstantSafetyState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeInstantSafetyState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeInstantSafetyState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.InstantSafetyState);

  @override
  set state(_i3.InstantSafetyState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.InstantSafetyState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeInstantSafetyState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeInstantSafetyState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.InstantSafetyState);

  @override
  _i5.Future<(_i3.InstantSafetySettings?, _i3.InstantSafetyStatus?)>
      performFetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #performFetch,
              [],
              {
                #forceRemote: forceRemote,
                #updateStatusOnly: updateStatusOnly,
              },
            ),
            returnValue: _i5.Future<
                (
                  _i3.InstantSafetySettings?,
                  _i3.InstantSafetyStatus?
                )>.value((null, null)),
            returnValueForMissingStub: _i5.Future<
                (
                  _i3.InstantSafetySettings?,
                  _i3.InstantSafetyStatus?
                )>.value((null, null)),
          ) as _i5
              .Future<(_i3.InstantSafetySettings?, _i3.InstantSafetyStatus?)>);

  @override
  _i5.Future<void> performSave() => (super.noSuchMethod(
        Invocation.method(
          #performSave,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setSafeBrowsingEnabled(bool? isEnabled) => super.noSuchMethod(
        Invocation.method(
          #setSafeBrowsingEnabled,
          [isEnabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSafeBrowsingProvider(_i3.InstantSafetyType? provider) =>
      super.noSuchMethod(
        Invocation.method(
          #setSafeBrowsingProvider,
          [provider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      _i3.InstantSafetyState?,
      _i3.InstantSafetyState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.InstantSafetyState? previous,
    _i3.InstantSafetyState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<_i3.InstantSafetyState> fetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
          {
            #forceRemote: forceRemote,
            #updateStatusOnly: updateStatusOnly,
          },
        ),
        returnValue:
            _i5.Future<_i3.InstantSafetyState>.value(_FakeInstantSafetyState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.InstantSafetyState>.value(_FakeInstantSafetyState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
      ) as _i5.Future<_i3.InstantSafetyState>);

  @override
  _i5.Future<_i3.InstantSafetyState> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue:
            _i5.Future<_i3.InstantSafetyState>.value(_FakeInstantSafetyState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.InstantSafetyState>.value(_FakeInstantSafetyState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i5.Future<_i3.InstantSafetyState>);

  @override
  void revert() => super.noSuchMethod(
        Invocation.method(
          #revert,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isDirty() => (super.noSuchMethod(
        Invocation.method(
          #isDirty,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void markAsSaved() => super.noSuchMethod(
        Invocation.method(
          #markAsSaved,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
