// Mocks generated by Mockito 5.4.5 from annotations
// in privacy_gui/test/mocks/mockito_specs/internet_settings_form_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/page/advanced_settings/internet_settings/providers/internet_settings_form_provider.dart'
    as _i3;
import 'package:privacy_gui/page/advanced_settings/internet_settings/providers/internet_settings_state.dart'
    as _i4;
import 'package:privacy_gui/page/advanced_settings/internet_settings/utils/internet_settings_form_validator.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.AutoDisposeNotifierProviderRef<T> {
  _FakeAutoDisposeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InternetSettingsIPv4FormValidityNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetSettingsIPv4FormValidityNotifier
    extends _i2.AutoDisposeNotifier<bool>
    with _i1.Mock
    implements _i3.InternetSettingsIPv4FormValidityNotifier {
  @override
  _i2.AutoDisposeNotifierProviderRef<bool> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAutoDisposeNotifierProviderRef_0<bool>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeAutoDisposeNotifierProviderRef_0<bool>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.AutoDisposeNotifierProviderRef<bool>);

  @override
  bool get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set state(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isWanFormValid(
    String? wanType,
    _i4.Ipv4Setting? ipv4Setting,
    _i5.InternetSettingsFormValidator? validator,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isWanFormValid,
          [
            wanType,
            ipv4Setting,
            validator,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void listenSelf(
    void Function(
      bool?,
      bool,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    bool? previous,
    bool? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [InternetSettingsIPv6FormValidityNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetSettingsIPv6FormValidityNotifier
    extends _i2.AutoDisposeNotifier<bool>
    with _i1.Mock
    implements _i3.InternetSettingsIPv6FormValidityNotifier {
  @override
  _i2.AutoDisposeNotifierProviderRef<bool> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAutoDisposeNotifierProviderRef_0<bool>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeAutoDisposeNotifierProviderRef_0<bool>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.AutoDisposeNotifierProviderRef<bool>);

  @override
  bool get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set state(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void listenSelf(
    void Function(
      bool?,
      bool,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    bool? previous,
    bool? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [OptionalSettingsFormValidityNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockOptionalSettingsFormValidityNotifier
    extends _i2.AutoDisposeNotifier<bool>
    with _i1.Mock
    implements _i3.OptionalSettingsFormValidityNotifier {
  @override
  _i2.AutoDisposeNotifierProviderRef<bool> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAutoDisposeNotifierProviderRef_0<bool>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeAutoDisposeNotifierProviderRef_0<bool>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.AutoDisposeNotifierProviderRef<bool>);

  @override
  bool get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set state(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void listenSelf(
    void Function(
      bool?,
      bool,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    bool? previous,
    bool? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
