// Mocks generated by Mockito 5.4.4 from annotations
// in privacy_gui/test/mocks/mockito_specs/ipv6_port_service_list_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/core/jnap/models/ipv6_firewall_rule.dart' as _i6;
import 'package:privacy_gui/page/advanced_settings/firewall/providers/ipv6_port_service_list_provider.dart'
    as _i4;
import 'package:privacy_gui/page/advanced_settings/firewall/providers/ipv6_port_service_list_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIpv6PortServiceListState_1 extends _i1.SmartFake
    implements _i3.Ipv6PortServiceListState {
  _FakeIpv6PortServiceListState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Ipv6PortServiceListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockIpv6PortServiceListNotifier extends _i2.Notifier<_i3.Ipv6PortServiceListState> with _i1.Mock
    implements _i4.Ipv6PortServiceListNotifier {
  @override
  _i2.NotifierProviderRef<_i3.Ipv6PortServiceListState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.Ipv6PortServiceListState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.Ipv6PortServiceListState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.Ipv6PortServiceListState>);

  @override
  _i3.Ipv6PortServiceListState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeIpv6PortServiceListState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeIpv6PortServiceListState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.Ipv6PortServiceListState);

  @override
  set state(_i3.Ipv6PortServiceListState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Ipv6PortServiceListState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeIpv6PortServiceListState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeIpv6PortServiceListState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.Ipv6PortServiceListState);

  @override
  _i5.Future<_i3.Ipv6PortServiceListState> fetch([bool? force = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [force],
        ),
        returnValue: _i5.Future<_i3.Ipv6PortServiceListState>.value(
            _FakeIpv6PortServiceListState_1(
          this,
          Invocation.method(
            #fetch,
            [force],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Ipv6PortServiceListState>.value(
                _FakeIpv6PortServiceListState_1(
          this,
          Invocation.method(
            #fetch,
            [force],
          ),
        )),
      ) as _i5.Future<_i3.Ipv6PortServiceListState>);

  @override
  _i5.Future<_i3.Ipv6PortServiceListState> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i5.Future<_i3.Ipv6PortServiceListState>.value(
            _FakeIpv6PortServiceListState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Ipv6PortServiceListState>.value(
                _FakeIpv6PortServiceListState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Ipv6PortServiceListState>);

  @override
  bool isExceedMax() => (super.noSuchMethod(
        Invocation.method(
          #isExceedMax,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void addRule(_i6.IPv6FirewallRule? rule) => super.noSuchMethod(
        Invocation.method(
          #addRule,
          [rule],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void editRule(
    int? index,
    _i6.IPv6FirewallRule? rule,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #editRule,
          [
            index,
            rule,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteRule(_i6.IPv6FirewallRule? rule) => super.noSuchMethod(
        Invocation.method(
          #deleteRule,
          [rule],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.Ipv6PortServiceListState? previous,
    _i3.Ipv6PortServiceListState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
