// Mocks generated by Mockito 5.4.6 from annotations
// in privacy_gui/test/mocks/mockito_specs/local_network_settings_service_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/core/jnap/actions/better_action.dart' as _i11;
import 'package:privacy_gui/core/jnap/actions/jnap_transaction.dart' as _i13;
import 'package:privacy_gui/core/jnap/command/base_command.dart' as _i7;
import 'package:privacy_gui/core/jnap/command/http/base_http_command.dart'
    as _i5;
import 'package:privacy_gui/core/jnap/jnap_command_executor_mixin.dart' as _i3;
import 'package:privacy_gui/core/jnap/models/lan_settings.dart' as _i8;
import 'package:privacy_gui/core/jnap/providers/side_effect_provider.dart'
    as _i12;
import 'package:privacy_gui/core/jnap/result/jnap_result.dart' as _i4;
import 'package:privacy_gui/core/jnap/router_repository.dart' as _i9;
import 'package:privacy_gui/core/jnap/spec/jnap_spec.dart' as _i6;
import 'package:privacy_gui/page/advanced_settings/local_network_settings/models/reservation_item_ui_model.dart'
    as _i15;
import 'package:privacy_gui/page/advanced_settings/local_network_settings/services/local_network_settings_service.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRef_0<State extends Object?> extends _i1.SmartFake
    implements _i2.Ref<State> {
  _FakeRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJNAPCommandExecutor_1<R> extends _i1.SmartFake
    implements _i3.JNAPCommandExecutor<R> {
  _FakeJNAPCommandExecutor_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJNAPSuccess_2 extends _i1.SmartFake implements _i4.JNAPSuccess {
  _FakeJNAPSuccess_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJNAPTransactionSuccessWrap_3 extends _i1.SmartFake
    implements _i4.JNAPTransactionSuccessWrap {
  _FakeJNAPTransactionSuccessWrap_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransactionHttpCommand_4 extends _i1.SmartFake
    implements _i5.TransactionHttpCommand {
  _FakeTransactionHttpCommand_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseCommand_5<R, S extends _i6.JNAPSpec<dynamic>>
    extends _i1.SmartFake implements _i7.BaseCommand<R, S> {
  _FakeBaseCommand_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouterLANSettings_6 extends _i1.SmartFake
    implements _i8.RouterLANSettings {
  _FakeRouterLANSettings_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RouterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterRepository extends _i1.Mock implements _i9.RouterRepository {
  @override
  _i2.Ref<Object?> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeRef_0<Object?>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeRef_0<Object?>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.Ref<Object?>);

  @override
  _i3.JNAPCommandExecutor<dynamic> get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeJNAPCommandExecutor_1<dynamic>(
          this,
          Invocation.getter(#executor),
        ),
        returnValueForMissingStub: _FakeJNAPCommandExecutor_1<dynamic>(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i3.JNAPCommandExecutor<dynamic>);

  @override
  bool get isEnableBTSetup => (super.noSuchMethod(
        Invocation.getter(#isEnableBTSetup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set enableBTSetup(bool? isEnable) => super.noSuchMethod(
        Invocation.setter(
          #enableBTSetup,
          isEnable,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i4.JNAPSuccess> send(
    _i11.JNAPAction? action, {
    Map<String, dynamic>? data = const {},
    Map<String, String>? extraHeaders = const {},
    bool? auth = false,
    _i9.CommandType? type,
    bool? fetchRemote = false,
    _i7.CacheLevel? cacheLevel,
    int? timeoutMs = 10000,
    int? retries = 1,
    _i12.JNAPSideEffectOverrides? sideEffectOverrides,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [action],
          {
            #data: data,
            #extraHeaders: extraHeaders,
            #auth: auth,
            #type: type,
            #fetchRemote: fetchRemote,
            #cacheLevel: cacheLevel,
            #timeoutMs: timeoutMs,
            #retries: retries,
            #sideEffectOverrides: sideEffectOverrides,
          },
        ),
        returnValue: _i10.Future<_i4.JNAPSuccess>.value(_FakeJNAPSuccess_2(
          this,
          Invocation.method(
            #send,
            [action],
            {
              #data: data,
              #extraHeaders: extraHeaders,
              #auth: auth,
              #type: type,
              #fetchRemote: fetchRemote,
              #cacheLevel: cacheLevel,
              #timeoutMs: timeoutMs,
              #retries: retries,
              #sideEffectOverrides: sideEffectOverrides,
            },
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i4.JNAPSuccess>.value(_FakeJNAPSuccess_2(
          this,
          Invocation.method(
            #send,
            [action],
            {
              #data: data,
              #extraHeaders: extraHeaders,
              #auth: auth,
              #type: type,
              #fetchRemote: fetchRemote,
              #cacheLevel: cacheLevel,
              #timeoutMs: timeoutMs,
              #retries: retries,
              #sideEffectOverrides: sideEffectOverrides,
            },
          ),
        )),
      ) as _i10.Future<_i4.JNAPSuccess>);

  @override
  _i10.Future<_i4.JNAPTransactionSuccessWrap> transaction(
    _i13.JNAPTransactionBuilder? builder, {
    bool? fetchRemote = false,
    _i7.CacheLevel? cacheLevel = _i7.CacheLevel.localCached,
    int? timeoutMs = 10000,
    int? retries = 1,
    _i12.JNAPSideEffectOverrides? sideEffectOverrides,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [builder],
          {
            #fetchRemote: fetchRemote,
            #cacheLevel: cacheLevel,
            #timeoutMs: timeoutMs,
            #retries: retries,
            #sideEffectOverrides: sideEffectOverrides,
          },
        ),
        returnValue: _i10.Future<_i4.JNAPTransactionSuccessWrap>.value(
            _FakeJNAPTransactionSuccessWrap_3(
          this,
          Invocation.method(
            #transaction,
            [builder],
            {
              #fetchRemote: fetchRemote,
              #cacheLevel: cacheLevel,
              #timeoutMs: timeoutMs,
              #retries: retries,
              #sideEffectOverrides: sideEffectOverrides,
            },
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i4.JNAPTransactionSuccessWrap>.value(
                _FakeJNAPTransactionSuccessWrap_3(
          this,
          Invocation.method(
            #transaction,
            [builder],
            {
              #fetchRemote: fetchRemote,
              #cacheLevel: cacheLevel,
              #timeoutMs: timeoutMs,
              #retries: retries,
              #sideEffectOverrides: sideEffectOverrides,
            },
          ),
        )),
      ) as _i10.Future<_i4.JNAPTransactionSuccessWrap>);

  @override
  _i10.Future<_i5.TransactionHttpCommand> createTransaction(
    List<Map<String, dynamic>>? payload, {
    bool? needAuth = false,
    required List<_i11.JNAPAction>? actions,
    bool? fetchRemote = false,
    _i7.CacheLevel? cacheLevel = _i7.CacheLevel.localCached,
    int? timeoutMs = 10000,
    int? retries = 1,
    _i9.CommandType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransaction,
          [payload],
          {
            #needAuth: needAuth,
            #actions: actions,
            #fetchRemote: fetchRemote,
            #cacheLevel: cacheLevel,
            #timeoutMs: timeoutMs,
            #retries: retries,
            #type: type,
          },
        ),
        returnValue: _i10.Future<_i5.TransactionHttpCommand>.value(
            _FakeTransactionHttpCommand_4(
          this,
          Invocation.method(
            #createTransaction,
            [payload],
            {
              #needAuth: needAuth,
              #actions: actions,
              #fetchRemote: fetchRemote,
              #cacheLevel: cacheLevel,
              #timeoutMs: timeoutMs,
              #retries: retries,
              #type: type,
            },
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.TransactionHttpCommand>.value(
                _FakeTransactionHttpCommand_4(
          this,
          Invocation.method(
            #createTransaction,
            [payload],
            {
              #needAuth: needAuth,
              #actions: actions,
              #fetchRemote: fetchRemote,
              #cacheLevel: cacheLevel,
              #timeoutMs: timeoutMs,
              #retries: retries,
              #type: type,
            },
          ),
        )),
      ) as _i10.Future<_i5.TransactionHttpCommand>);

  @override
  _i10.Future<
      _i7
      .BaseCommand<_i4.JNAPResult, _i6.JNAPCommandSpec<dynamic>>> createCommand(
    String? action, {
    Map<String, dynamic>? data = const {},
    Map<String, String>? extraHeaders = const {},
    bool? needAuth = false,
    _i9.CommandType? type,
    bool? fetchRemote = false,
    _i7.CacheLevel? cacheLevel = _i7.CacheLevel.localCached,
    int? timeoutMs = 10000,
    int? retries = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCommand,
          [action],
          {
            #data: data,
            #extraHeaders: extraHeaders,
            #needAuth: needAuth,
            #type: type,
            #fetchRemote: fetchRemote,
            #cacheLevel: cacheLevel,
            #timeoutMs: timeoutMs,
            #retries: retries,
          },
        ),
        returnValue: _i10.Future<
                _i7.BaseCommand<_i4.JNAPResult,
                    _i6.JNAPCommandSpec<dynamic>>>.value(
            _FakeBaseCommand_5<_i4.JNAPResult, _i6.JNAPCommandSpec<dynamic>>(
          this,
          Invocation.method(
            #createCommand,
            [action],
            {
              #data: data,
              #extraHeaders: extraHeaders,
              #needAuth: needAuth,
              #type: type,
              #fetchRemote: fetchRemote,
              #cacheLevel: cacheLevel,
              #timeoutMs: timeoutMs,
              #retries: retries,
            },
          ),
        )),
        returnValueForMissingStub: _i10.Future<
                _i7.BaseCommand<_i4.JNAPResult,
                    _i6.JNAPCommandSpec<dynamic>>>.value(
            _FakeBaseCommand_5<_i4.JNAPResult, _i6.JNAPCommandSpec<dynamic>>(
          this,
          Invocation.method(
            #createCommand,
            [action],
            {
              #data: data,
              #extraHeaders: extraHeaders,
              #needAuth: needAuth,
              #type: type,
              #fetchRemote: fetchRemote,
              #cacheLevel: cacheLevel,
              #timeoutMs: timeoutMs,
              #retries: retries,
            },
          ),
        )),
      ) as _i10.Future<
          _i7.BaseCommand<_i4.JNAPResult, _i6.JNAPCommandSpec<dynamic>>>);

  @override
  _i10.Stream<_i4.JNAPResult> scheduledCommand({
    required _i11.JNAPAction? action,
    int? retryDelayInMilliSec = 5000,
    int? maxRetry = 10,
    int? firstDelayInMilliSec = 3000,
    Map<String, dynamic>? data = const {},
    bool Function(_i4.JNAPResult)? condition,
    dynamic Function(bool)? onCompleted,
    int? requestTimeoutOverride,
    bool? auth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduledCommand,
          [],
          {
            #action: action,
            #retryDelayInMilliSec: retryDelayInMilliSec,
            #maxRetry: maxRetry,
            #firstDelayInMilliSec: firstDelayInMilliSec,
            #data: data,
            #condition: condition,
            #onCompleted: onCompleted,
            #requestTimeoutOverride: requestTimeoutOverride,
            #auth: auth,
          },
        ),
        returnValue: _i10.Stream<_i4.JNAPResult>.empty(),
        returnValueForMissingStub: _i10.Stream<_i4.JNAPResult>.empty(),
      ) as _i10.Stream<_i4.JNAPResult>);
}

/// A class which mocks [LocalNetworkSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalNetworkSettingsService extends _i1.Mock
    implements _i14.LocalNetworkSettingsService {
  @override
  _i10.Future<_i8.RouterLANSettings> fetchLANSettings(
          {bool? forceRemote = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLANSettings,
          [],
          {#forceRemote: forceRemote},
        ),
        returnValue:
            _i10.Future<_i8.RouterLANSettings>.value(_FakeRouterLANSettings_6(
          this,
          Invocation.method(
            #fetchLANSettings,
            [],
            {#forceRemote: forceRemote},
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i8.RouterLANSettings>.value(_FakeRouterLANSettings_6(
          this,
          Invocation.method(
            #fetchLANSettings,
            [],
            {#forceRemote: forceRemote},
          ),
        )),
      ) as _i10.Future<_i8.RouterLANSettings>);

  @override
  _i10.Future<void> saveReservations({
    required String? routerIp,
    required int? networkPrefixLength,
    required String? hostName,
    required bool? isDHCPEnabled,
    required String? firstClientIP,
    required String? lastClientIP,
    required int? leaseMinutes,
    String? dns1,
    String? dns2,
    String? dns3,
    String? wins,
    required List<_i15.DHCPReservationUIModel>? reservations,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveReservations,
          [],
          {
            #routerIp: routerIp,
            #networkPrefixLength: networkPrefixLength,
            #hostName: hostName,
            #isDHCPEnabled: isDHCPEnabled,
            #firstClientIP: firstClientIP,
            #lastClientIP: lastClientIP,
            #leaseMinutes: leaseMinutes,
            #dns1: dns1,
            #dns2: dns2,
            #dns3: dns3,
            #wins: wins,
            #reservations: reservations,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  List<_i15.DHCPReservationUIModel> convertFromJNAPList(
          List<_i8.DHCPReservation>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertFromJNAPList,
          [list],
        ),
        returnValue: <_i15.DHCPReservationUIModel>[],
        returnValueForMissingStub: <_i15.DHCPReservationUIModel>[],
      ) as List<_i15.DHCPReservationUIModel>);
}
