// Mocks generated by Mockito 5.4.6 from annotations
// in privacy_gui/test/mocks/mockito_specs/node_light_settings_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/core/jnap/models/node_light_settings.dart' as _i3;
import 'package:privacy_gui/core/jnap/providers/node_light_settings_provider.dart'
    as _i4;
import 'package:privacy_gui/page/nodes/providers/node_detail_state.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNodeLightSettings_1 extends _i1.SmartFake
    implements _i3.NodeLightSettings {
  _FakeNodeLightSettings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NodeLightSettingsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeLightSettingsNotifier extends _i2.Notifier<_i3.NodeLightSettings>
    with _i1.Mock
    implements _i4.NodeLightSettingsNotifier {
  @override
  _i5.NodeLightStatus get currentStatus => (super.noSuchMethod(
        Invocation.getter(#currentStatus),
        returnValue: _i5.NodeLightStatus.on,
        returnValueForMissingStub: _i5.NodeLightStatus.on,
      ) as _i5.NodeLightStatus);

  @override
  _i2.NotifierProviderRef<_i3.NodeLightSettings> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.NodeLightSettings>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.NodeLightSettings>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.NodeLightSettings>);

  @override
  _i3.NodeLightSettings get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeNodeLightSettings_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeNodeLightSettings_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.NodeLightSettings);

  @override
  set state(_i3.NodeLightSettings? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.NodeLightSettings build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeNodeLightSettings_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeNodeLightSettings_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.NodeLightSettings);

  @override
  _i6.Future<_i3.NodeLightSettings> fetch([bool? forceRemote = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [forceRemote],
        ),
        returnValue:
            _i6.Future<_i3.NodeLightSettings>.value(_FakeNodeLightSettings_1(
          this,
          Invocation.method(
            #fetch,
            [forceRemote],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.NodeLightSettings>.value(_FakeNodeLightSettings_1(
          this,
          Invocation.method(
            #fetch,
            [forceRemote],
          ),
        )),
      ) as _i6.Future<_i3.NodeLightSettings>);

  @override
  _i6.Future<_i3.NodeLightSettings> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue:
            _i6.Future<_i3.NodeLightSettings>.value(_FakeNodeLightSettings_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.NodeLightSettings>.value(_FakeNodeLightSettings_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i6.Future<_i3.NodeLightSettings>);

  @override
  void setSettings(_i3.NodeLightSettings? settings) => super.noSuchMethod(
        Invocation.method(
          #setSettings,
          [settings],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      _i3.NodeLightSettings?,
      _i3.NodeLightSettings,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.NodeLightSettings? previous,
    _i3.NodeLightSettings? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
