// Mocks generated by Mockito 5.4.6 from annotations
// in privacy_gui/test/mocks/mockito_specs/pnp_isp_settings_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/page/advanced_settings/internet_settings/providers/_providers.dart'
    as _i5;
import 'package:privacy_gui/page/instant_setup/troubleshooter/providers/pnp_isp_settings_provider.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PnpIspSettingsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPnpIspSettingsNotifier extends _i2.Notifier<_i3.PnpIspSettingsStatus>
    with _i1.Mock
    implements _i3.PnpIspSettingsNotifier {
  @override
  _i2.NotifierProviderRef<_i3.PnpIspSettingsStatus> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.PnpIspSettingsStatus>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.PnpIspSettingsStatus>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.PnpIspSettingsStatus>);

  @override
  _i3.PnpIspSettingsStatus get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i3.PnpIspSettingsStatus.initial,
        returnValueForMissingStub: _i3.PnpIspSettingsStatus.initial,
      ) as _i3.PnpIspSettingsStatus);

  @override
  set state(_i3.PnpIspSettingsStatus? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.PnpIspSettingsStatus build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _i3.PnpIspSettingsStatus.initial,
        returnValueForMissingStub: _i3.PnpIspSettingsStatus.initial,
      ) as _i3.PnpIspSettingsStatus);

  @override
  _i4.Future<void> saveAndVerifySettings(_i5.InternetSettings? newSettings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAndVerifySettings,
          [newSettings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void listenSelf(
    void Function(
      _i3.PnpIspSettingsStatus?,
      _i3.PnpIspSettingsStatus,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.PnpIspSettingsStatus? previous,
    _i3.PnpIspSettingsStatus? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
