// Mocks generated by Mockito 5.4.6 from annotations
// in privacy_gui/test/mocks/mockito_specs/pnp_troubleshooter_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/page/instant_setup/troubleshooter/providers/pnp_troubleshooter_provider.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePnpTroubleshooterState_1 extends _i1.SmartFake
    implements _i3.PnpTroubleshooterState {
  _FakePnpTroubleshooterState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PnpTroubleshooterNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPnpTroubleshooterNotifier
    extends _i2.Notifier<_i3.PnpTroubleshooterState>
    with _i1.Mock
    implements _i3.PnpTroubleshooterNotifier {
  @override
  _i2.NotifierProviderRef<_i3.PnpTroubleshooterState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.PnpTroubleshooterState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.PnpTroubleshooterState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.PnpTroubleshooterState>);

  @override
  _i3.PnpTroubleshooterState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePnpTroubleshooterState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakePnpTroubleshooterState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.PnpTroubleshooterState);

  @override
  set state(_i3.PnpTroubleshooterState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.PnpTroubleshooterState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakePnpTroubleshooterState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakePnpTroubleshooterState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.PnpTroubleshooterState);

  @override
  void setEnterRoute(String? route) => super.noSuchMethod(
        Invocation.method(
          #setEnterRoute,
          [route],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      _i3.PnpTroubleshooterState?,
      _i3.PnpTroubleshooterState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.PnpTroubleshooterState? previous,
    _i3.PnpTroubleshooterState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
