// Mocks generated by Mockito 5.4.6 from annotations
// in privacy_gui/test/mocks/mockito_specs/pnp_isp_service_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/page/advanced_settings/internet_settings/models/internet_settings_enums.dart'
    as _i4;
import 'package:privacy_gui/page/instant_setup/troubleshooter/services/pnp_isp_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PnpIspService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPnpIspService extends _i1.Mock implements _i2.PnpIspService {
  @override
  _i3.Future<bool> verifyNewSettings(_i4.WanType? settingWanType) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyNewSettings,
          [settingWanType],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
