// Mocks generated by Mockito 5.4.5 from annotations
// in privacy_gui/test/mocks/mockito_specs/port_range_triggering_list_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/core/jnap/models/port_range_triggering_rule.dart'
    as _i5;
import 'package:privacy_gui/page/advanced_settings/apps_and_gaming/ports/_ports.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePortRangeTriggeringListState_1 extends _i1.SmartFake
    implements _i3.PortRangeTriggeringListState {
  _FakePortRangeTriggeringListState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PortRangeTriggeringListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortRangeTriggeringListNotifier
    extends _i2.Notifier<_i3.PortRangeTriggeringListState>
    with _i1.Mock
    implements _i3.PortRangeTriggeringListNotifier {
  @override
  _i2.NotifierProviderRef<_i3.PortRangeTriggeringListState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue:
            _FakeNotifierProviderRef_0<_i3.PortRangeTriggeringListState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.PortRangeTriggeringListState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.PortRangeTriggeringListState>);

  @override
  _i3.PortRangeTriggeringListState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePortRangeTriggeringListState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakePortRangeTriggeringListState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.PortRangeTriggeringListState);

  @override
  set state(_i3.PortRangeTriggeringListState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.PortRangeTriggeringListState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakePortRangeTriggeringListState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakePortRangeTriggeringListState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.PortRangeTriggeringListState);

  @override
  _i4.Future<
      (
        _i5.PortRangeTriggeringRuleList?,
        _i3.PortRangeTriggeringListStatus?
      )> performFetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performFetch,
          [],
          {
            #forceRemote: forceRemote,
            #updateStatusOnly: updateStatusOnly,
          },
        ),
        returnValue: _i4.Future<
            (
              _i5.PortRangeTriggeringRuleList?,
              _i3.PortRangeTriggeringListStatus?
            )>.value((null, null)),
        returnValueForMissingStub: _i4.Future<
            (
              _i5.PortRangeTriggeringRuleList?,
              _i3.PortRangeTriggeringListStatus?
            )>.value((null, null)),
      ) as _i4.Future<
          (
            _i5.PortRangeTriggeringRuleList?,
            _i3.PortRangeTriggeringListStatus?
          )>);

  @override
  _i4.Future<void> performSave() => (super.noSuchMethod(
        Invocation.method(
          #performSave,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool isExceedMax() => (super.noSuchMethod(
        Invocation.method(
          #isExceedMax,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void addRule(_i5.PortRangeTriggeringRule? rule) => super.noSuchMethod(
        Invocation.method(
          #addRule,
          [rule],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void editRule(
    int? index,
    _i5.PortRangeTriggeringRule? rule,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #editRule,
          [
            index,
            rule,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteRule(_i5.PortRangeTriggeringRule? rule) => super.noSuchMethod(
        Invocation.method(
          #deleteRule,
          [rule],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      _i3.PortRangeTriggeringListState?,
      _i3.PortRangeTriggeringListState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.PortRangeTriggeringListState? previous,
    _i3.PortRangeTriggeringListState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<_i3.PortRangeTriggeringListState> fetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
          {
            #forceRemote: forceRemote,
            #updateStatusOnly: updateStatusOnly,
          },
        ),
        returnValue: _i4.Future<_i3.PortRangeTriggeringListState>.value(
            _FakePortRangeTriggeringListState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.PortRangeTriggeringListState>.value(
                _FakePortRangeTriggeringListState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
      ) as _i4.Future<_i3.PortRangeTriggeringListState>);

  @override
  _i4.Future<_i3.PortRangeTriggeringListState> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i4.Future<_i3.PortRangeTriggeringListState>.value(
            _FakePortRangeTriggeringListState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.PortRangeTriggeringListState>.value(
                _FakePortRangeTriggeringListState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i4.Future<_i3.PortRangeTriggeringListState>);

  @override
  void revert() => super.noSuchMethod(
        Invocation.method(
          #revert,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isDirty() => (super.noSuchMethod(
        Invocation.method(
          #isDirty,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void markAsSaved() => super.noSuchMethod(
        Invocation.method(
          #markAsSaved,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
