// Mocks generated by Mockito 5.4.6 from annotations
// in privacy_gui/test/mocks/mockito_specs/side_effect_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/core/data/providers/side_effect_provider.dart'
    as _i3;
import 'package:privacy_gui/core/jnap/result/jnap_result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJNAPSideEffect_1 extends _i1.SmartFake
    implements _i3.SideEffectState {
  _FakeJNAPSideEffect_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJNAPResult_2 extends _i1.SmartFake implements _i4.JNAPResult {
  _FakeJNAPResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SideEffectNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSideEffectNotifier extends _i2.Notifier<_i3.SideEffectState>
    with _i1.Mock
    implements _i3.SideEffectNotifier {
  @override
  _i2.NotifierProviderRef<_i3.SideEffectState> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.SideEffectState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.SideEffectState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.SideEffectState>);

  @override
  _i3.SideEffectState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeJNAPSideEffect_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeJNAPSideEffect_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.SideEffectState);

  @override
  set state(_i3.SideEffectState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.SideEffectState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeJNAPSideEffect_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeJNAPSideEffect_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.SideEffectState);

  @override
  _i5.Future<dynamic> manualDeviceRestart({_i3.SideEffectPollConfig? config}) =>
      (super.noSuchMethod(
        Invocation.method(
          #manualDeviceRestart,
          [],
          {#config: config},
        ),
        returnValue: _i5.Future<dynamic>.value(),
        returnValueForMissingStub: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<_i4.JNAPResult> handleSideEffect(
    _i4.JNAPResult? result, {
    _i3.SideEffectPollConfig? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleSideEffect,
          [result],
          {#config: config},
        ),
        returnValue: _i5.Future<_i4.JNAPResult>.value(_FakeJNAPResult_2(
          this,
          Invocation.method(
            #handleSideEffect,
            [result],
            {#config: config},
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i4.JNAPResult>.value(_FakeJNAPResult_2(
          this,
          Invocation.method(
            #handleSideEffect,
            [result],
            {#config: config},
          ),
        )),
      ) as _i5.Future<_i4.JNAPResult>);

  @override
  _i5.Future<bool> poll({
    required _i5.Future<(bool, _i4.JNAPResult?)> Function()? pollFunc,
    int? retryDelayInSec = 5,
    int? maxRetry = -1,
    int? maxPollTimeInSec = -1,
    int? timeDelayStartInSec = 3,
    bool Function()? condition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #poll,
          [],
          {
            #pollFunc: pollFunc,
            #retryDelayInSec: retryDelayInSec,
            #maxRetry: maxRetry,
            #maxPollTimeInSec: maxPollTimeInSec,
            #timeDelayStartInSec: timeDelayStartInSec,
            #condition: condition,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<(bool, _i4.JNAPResult?)> testRouterFullyBootedUp() =>
      (super.noSuchMethod(
        Invocation.method(
          #testRouterFullyBootedUp,
          [],
        ),
        returnValue: _i5.Future<(bool, _i4.JNAPResult?)>.value((false, null)),
        returnValueForMissingStub:
            _i5.Future<(bool, _i4.JNAPResult?)>.value((false, null)),
      ) as _i5.Future<(bool, _i4.JNAPResult?)>);

  @override
  _i5.Future<(bool, _i4.JNAPResult?)> testRouterReconnected() =>
      (super.noSuchMethod(
        Invocation.method(
          #testRouterReconnected,
          [],
        ),
        returnValue: _i5.Future<(bool, _i4.JNAPResult?)>.value((false, null)),
        returnValueForMissingStub:
            _i5.Future<(bool, _i4.JNAPResult?)>.value((false, null)),
      ) as _i5.Future<(bool, _i4.JNAPResult?)>);

  @override
  void listenSelf(
    void Function(
      _i3.SideEffectState?,
      _i3.SideEffectState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.SideEffectState? previous,
    _i3.SideEffectState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
