// Mocks generated by Mockito 5.4.4 from annotations
// in privacy_gui/test/mocks/mockito_specs/static_routing_rule_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/core/jnap/models/get_routing_settings.dart' as _i5;
import 'package:privacy_gui/page/advanced_settings/static_routing/providers/static_routing_rule_provider.dart'
    as _i4;
import 'package:privacy_gui/page/advanced_settings/static_routing/providers/static_routing_rule_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStaticRoutingRuleState_1 extends _i1.SmartFake
    implements _i3.StaticRoutingRuleState {
  _FakeStaticRoutingRuleState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StaticRoutingRuleNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockStaticRoutingRuleNotifier extends _i2.Notifier<
    _i3.StaticRoutingRuleState>
    with _i1.Mock
    implements _i4.StaticRoutingRuleNotifier {
  @override
  _i2.NotifierProviderRef<_i3.StaticRoutingRuleState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.StaticRoutingRuleState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.StaticRoutingRuleState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.StaticRoutingRuleState>);

  @override
  _i3.StaticRoutingRuleState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeStaticRoutingRuleState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeStaticRoutingRuleState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.StaticRoutingRuleState);

  @override
  set state(_i3.StaticRoutingRuleState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.StaticRoutingRuleState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeStaticRoutingRuleState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeStaticRoutingRuleState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.StaticRoutingRuleState);

  @override
  void init(
    List<_i5.NamedStaticRouteEntry>? rules,
    _i5.NamedStaticRouteEntry? rule,
    int? index,
    String? routerIp,
    String? subnetMask,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #init,
          [
            rules,
            rule,
            index,
            routerIp,
            subnetMask,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateRule(_i5.NamedStaticRouteEntry? rule) => super.noSuchMethod(
        Invocation.method(
          #updateRule,
          [rule],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isNameValid(String name) => (super.noSuchMethod(
        Invocation.method(
          #isRuleValid,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isRuleValid() => (super.noSuchMethod(
        Invocation.method(
          #isRuleValid,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isValidSubnetMask(int? perfixLength) => (super.noSuchMethod(
        Invocation.method(
          #isValidSubnetMask,
          [perfixLength],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isValidIpAddress(
    String? ipAddress, [
    bool? localIPOnly = false,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #isValidIpAddress,
          [
            ipAddress,
            localIPOnly,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void listenSelf(
    void Function(
      _i3.StaticRoutingRuleState?,
      _i3.StaticRoutingRuleState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.StaticRoutingRuleState? previous,
    _i3.StaticRoutingRuleState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
