// Mocks generated by Mockito 5.4.5 from annotations
// in privacy_gui/test/mocks/mockito_specs/vpn_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/page/vpn/models/vpn_models.dart' as _i6;
import 'package:privacy_gui/page/vpn/providers/vpn_notifier.dart' as _i4;
import 'package:privacy_gui/page/vpn/providers/vpn_state.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVPNState_1 extends _i1.SmartFake implements _i3.VPNState {
  _FakeVPNState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VPNNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockVPNNotifier extends _i2.Notifier<_i3.VPNState> with _i1.Mock implements _i4.VPNNotifier {
  @override
  _i2.NotifierProviderRef<_i3.VPNState> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.VPNState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeNotifierProviderRef_0<_i3.VPNState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.VPNState>);

  @override
  _i3.VPNState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeVPNState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeVPNState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.VPNState);

  @override
  set state(_i3.VPNState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.VPNState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeVPNState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeVPNState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.VPNState);

  @override
  _i5.Future<_i3.VPNState> fetch([bool? force = false, bool? statusOnly = false]) => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [force, statusOnly],
        ),
        returnValue: _i5.Future<_i3.VPNState>.value(_FakeVPNState_1(
          this,
          Invocation.method(
            #fetch,
            [force, statusOnly],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.VPNState>.value(_FakeVPNState_1(
          this,
          Invocation.method(
            #fetch,
            [force, statusOnly],
          ),
        )),
      ) as _i5.Future<_i3.VPNState>);

  @override
  _i5.Future<_i3.VPNState> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i5.Future<_i3.VPNState>.value(_FakeVPNState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.VPNState>.value(_FakeVPNState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i5.Future<_i3.VPNState>);

  @override
  _i5.Future<void> setEditingCredentials(bool? isEditing) =>
      (super.noSuchMethod(
        Invocation.method(
          #setEditingCredentials,
          [isEditing],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setVPNUser(_i6.VPNUserCredentials? credentials) =>
      (super.noSuchMethod(
        Invocation.method(
          #setVPNUser,
          [credentials],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setVPNGateway(_i6.VPNGatewaySettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #setVPNGateway,
          [settings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setVPNService(_i6.VPNServiceSetSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #setVPNService,
          [settings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setTunneledUser(String? ipAddress) => (super.noSuchMethod(
        Invocation.method(
          #setTunneledUser,
          [ipAddress],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.VPNState> testVPNConnection() => (super.noSuchMethod(
        Invocation.method(
          #testVPNConnection,
          [],
        ),
        returnValue: _i5.Future<_i3.VPNState>.value(_FakeVPNState_1(
          this,
          Invocation.method(
            #testVPNConnection,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.VPNState>.value(_FakeVPNState_1(
          this,
          Invocation.method(
            #testVPNConnection,
            [],
          ),
        )),
      ) as _i5.Future<_i3.VPNState>);

  @override
  void listenSelf(
    void Function(
      _i3.VPNState?,
      _i3.VPNState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.VPNState? previous,
    _i3.VPNState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
