// Mocks generated by Mockito 5.4.6 from annotations
// in privacy_gui/test/mocks/mockito_specs/wifi_bundle_settings_notifier_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/page/instant_privacy/providers/instant_privacy_state.dart'
    as _i7;
import 'package:privacy_gui/page/wifi_settings/providers/wifi_bundle_provider.dart'
    as _i4;
import 'package:privacy_gui/page/wifi_settings/providers/wifi_bundle_state.dart'
    as _i3;
import 'package:privacy_gui/page/wifi_settings/providers/wifi_item.dart' as _i6;
import 'package:privacy_gui/page/wifi_settings/providers/wifi_state.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWifiBundleState_1 extends _i1.SmartFake
    implements _i3.WifiBundleState {
  _FakeWifiBundleState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WifiBundleNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWifiBundleNotifier extends _i2.Notifier<_i3.WifiBundleState>
    with _i1.Mock
    implements _i4.WifiBundleNotifier {
  @override
  _i2.NotifierProviderRef<_i3.WifiBundleState> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.WifiBundleState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i3.WifiBundleState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.WifiBundleState>);

  @override
  _i3.WifiBundleState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeWifiBundleState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeWifiBundleState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.WifiBundleState);

  @override
  set state(_i3.WifiBundleState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.WifiBundleState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeWifiBundleState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeWifiBundleState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.WifiBundleState);

  @override
  _i5.Future<(_i3.WifiBundleSettings?, _i3.WifiBundleStatus?)> performFetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performFetch,
          [],
          {
            #forceRemote: forceRemote,
            #updateStatusOnly: updateStatusOnly,
          },
        ),
        returnValue:
            _i5.Future<(_i3.WifiBundleSettings?, _i3.WifiBundleStatus?)>.value(
                (null, null)),
        returnValueForMissingStub:
            _i5.Future<(_i3.WifiBundleSettings?, _i3.WifiBundleStatus?)>.value(
                (null, null)),
      ) as _i5.Future<(_i3.WifiBundleSettings?, _i3.WifiBundleStatus?)>);

  @override
  _i5.Future<void> performSave() => (super.noSuchMethod(
        Invocation.method(
          #performSave,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveToggleEnabled({
    required List<String>? radios,
    required bool? enabled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveToggleEnabled,
          [],
          {
            #radios: radios,
            #enabled: enabled,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setWiFiSSID(
    String? ssid, [
    _i6.WifiRadioBand? band,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #setWiFiSSID,
          [
            ssid,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWiFiPassword(
    String? password, [
    _i6.WifiRadioBand? band,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #setWiFiPassword,
          [
            password,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWiFiEnabled(
    bool? isEnabled, [
    _i6.WifiRadioBand? band,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #setWiFiEnabled,
          [
            isEnabled,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWiFiSecurityType(
    _i6.WifiSecurityType? type,
    _i6.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setWiFiSecurityType,
          [
            type,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWiFiMode(
    _i6.WifiWirelessMode? mode,
    _i6.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setWiFiMode,
          [
            mode,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEnableBoardcast(
    bool? isEnabled,
    _i6.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setEnableBoardcast,
          [
            isEnabled,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setChannelWidth(
    _i6.WifiChannelWidth? channelWidth,
    _i6.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setChannelWidth,
          [
            channelWidth,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setChannel(
    int? channel,
    _i6.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setChannel,
          [
            channel,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSimpleMode(bool? isSimple) => super.noSuchMethod(
        Invocation.method(
          #setSimpleMode,
          [isSimple],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSimpleModeWifi(_i6.WiFiItem? wifi) => super.noSuchMethod(
        Invocation.method(
          #setSimpleModeWifi,
          [wifi],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setClientSteeringEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setClientSteeringEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNodesSteeringEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setNodesSteeringEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setIptvEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setIptvEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDFSEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setDFSEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMLOEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setMLOEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAirtimeFairnessEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setAirtimeFairnessEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMacFilterMode(_i7.MacFilterMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setMacFilterMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMacFilterSelection(
    List<String>? selections, [
    bool? isDeny = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #setMacFilterSelection,
          [
            selections,
            isDeny,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeMacFilterSelection(
    List<String>? selection, [
    bool? isDeny = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #removeMacFilterSelection,
          [
            selection,
            isDeny,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMacAddressList(List<String>? macAddressList) => super.noSuchMethod(
        Invocation.method(
          #setMacAddressList,
          [macAddressList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool validateWifiListSettings(_i8.WiFiListSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateWifiListSettings,
          [settings],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool checkingMLOSettingsConflicts(
    Map<_i6.WifiRadioBand, _i6.WiFiItem>? radios, {
    bool? isMloEnabled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkingMLOSettingsConflicts,
          [radios],
          {#isMloEnabled: isMloEnabled},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void listenSelf(
    void Function(
      _i3.WifiBundleState?,
      _i3.WifiBundleState,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.WifiBundleState? previous,
    _i3.WifiBundleState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<_i3.WifiBundleState> fetch({
    bool? forceRemote = false,
    bool? updateStatusOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
          {
            #forceRemote: forceRemote,
            #updateStatusOnly: updateStatusOnly,
          },
        ),
        returnValue:
            _i5.Future<_i3.WifiBundleState>.value(_FakeWifiBundleState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.WifiBundleState>.value(_FakeWifiBundleState_1(
          this,
          Invocation.method(
            #fetch,
            [],
            {
              #forceRemote: forceRemote,
              #updateStatusOnly: updateStatusOnly,
            },
          ),
        )),
      ) as _i5.Future<_i3.WifiBundleState>);

  @override
  _i5.Future<_i3.WifiBundleState> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue:
            _i5.Future<_i3.WifiBundleState>.value(_FakeWifiBundleState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.WifiBundleState>.value(_FakeWifiBundleState_1(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i5.Future<_i3.WifiBundleState>);

  @override
  void revert() => super.noSuchMethod(
        Invocation.method(
          #revert,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isDirty() => (super.noSuchMethod(
        Invocation.method(
          #isDirty,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void markAsSaved() => super.noSuchMethod(
        Invocation.method(
          #markAsSaved,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
