// ignore_for_file: avoid_print

/// Extracts TR-181 device model paths from the BBF XML specification
/// and generates a Dart const file for autocomplete support.
///
/// Usage:
///   dart run tools/tr181_path_extractor.dart [xml_path] [output_path]
///
/// Defaults:
///   xml_path:    doc/usp/tr-181-2-20-0-usp-full.xml
///   output_path: lib/generated/tr181_paths.g.dart

import 'dart:io';

import 'package:xml/xml.dart';

void main(List<String> args) {
  final xmlPath =
      args.isNotEmpty ? args[0] : 'doc/usp/tr-181-2-20-0-usp-full.xml';
  final outputPath =
      args.length > 1 ? args[1] : 'lib/generated/tr181_paths.g.dart';

  final xmlFile = File(xmlPath);
  if (!xmlFile.existsSync()) {
    print('ERROR: XML file not found: $xmlPath');
    exit(1);
  }

  print('Parsing $xmlPath ...');
  final document = XmlDocument.parse(xmlFile.readAsStringSync());

  // Find <model> element
  final model = document.findAllElements('model').firstOrNull;
  if (model == null) {
    print('ERROR: No <model> element found in XML');
    exit(1);
  }

  final entries = <_PathEntry>[];
  var objectCount = 0;
  var paramCount = 0;
  var commandCount = 0;
  var eventCount = 0;

  // Iterate direct <object> children of <model>
  for (final obj in model.findElements('object')) {
    final objectName = obj.getAttribute('name');
    if (objectName == null || !objectName.startsWith('Device.')) continue;

    final objectAccess = obj.getAttribute('access') ?? 'readOnly';
    entries.add(_PathEntry(objectName, 'object', objectAccess));
    objectCount++;

    // Direct child <parameter> elements (skip those inside <input>/<output>)
    for (final param in obj.children.whereType<XmlElement>()) {
      if (param.name.local == 'parameter') {
        final paramName = param.getAttribute('name');
        if (paramName == null) continue;
        final paramAccess = param.getAttribute('access') ?? 'readOnly';
        entries
            .add(_PathEntry('$objectName$paramName', 'parameter', paramAccess));
        paramCount++;
      } else if (param.name.local == 'command') {
        final cmdName = param.getAttribute('name');
        if (cmdName == null) continue;
        const cmdAccess = 'readWrite'; // Commands are writable by nature
        entries.add(_PathEntry('$objectName$cmdName', 'command', cmdAccess));
        commandCount++;
      } else if (param.name.local == 'event') {
        final evtName = param.getAttribute('name');
        if (evtName == null) continue;
        entries.add(_PathEntry('$objectName$evtName', 'event', 'readOnly'));
        eventCount++;
      }
    }
  }

  // Sort alphabetically
  entries.sort((a, b) => a.path.compareTo(b.path));

  // Generate Dart file
  final buffer = StringBuffer();
  buffer.writeln('// AUTO-GENERATED CODE - DO NOT EDIT');
  buffer.writeln('// Generated by tools/tr181_path_extractor.dart');
  buffer.writeln('// Source: TR-181 Issue 2, Amendment 20 (Device:2.20)');
  buffer.writeln(
      '// Total: ${entries.length} entries ($objectCount objects, $paramCount parameters, $commandCount commands, $eventCount events)');
  buffer.writeln();
  buffer.writeln("enum Tr181PathType { object, parameter, command, event }");
  buffer.writeln();
  buffer.writeln("enum Tr181Access { readOnly, readWrite, writeOnceReadOnly }");
  buffer.writeln();
  buffer.writeln('class Tr181PathEntry {');
  buffer.writeln('  final String path;');
  buffer.writeln('  final Tr181PathType type;');
  buffer.writeln('  final Tr181Access access;');
  buffer.writeln('  const Tr181PathEntry(this.path, this.type, this.access);');
  buffer.writeln('}');
  buffer.writeln();
  buffer.writeln('const List<Tr181PathEntry> tr181Paths = [');

  for (final entry in entries) {
    final typeStr = 'Tr181PathType.${entry.type}';
    final accessStr = 'Tr181Access.${entry.access}';
    buffer.writeln(
        "  Tr181PathEntry('${_escape(entry.path)}', $typeStr, $accessStr),");
  }

  buffer.writeln('];');

  // Write output
  final outputFile = File(outputPath);
  outputFile.parent.createSync(recursive: true);
  outputFile.writeAsStringSync(buffer.toString());

  print('Generated $outputPath');
  print('  Objects:    $objectCount');
  print('  Parameters: $paramCount');
  print('  Commands:   $commandCount');
  print('  Events:     $eventCount');
  print('  Total:      ${entries.length}');
}

class _PathEntry {
  final String path;
  final String type;
  final String access;
  _PathEntry(this.path, this.type, this.access);
}

String _escape(String s) => s.replaceAll("'", "\\'");
