// Mocks generated by Mockito 5.4.4 from annotations
// in privacy_gui/test/page/wifi_settings/views/localizations/wifi_main_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:privacy_gui/page/wifi_settings/_wifi_settings.dart' as _i4;
import 'package:privacy_gui/page/wifi_settings/providers/guest_wifi_provider.dart'
    as _i8;
import 'package:privacy_gui/page/wifi_settings/providers/guest_wifi_state.dart'
    as _i5;
import 'package:privacy_gui/page/wifi_settings/providers/wifi_state.dart'
    as _i3;
import 'package:privacy_gui/page/wifi_settings/views/wifi_list_view.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWiFiState_1 extends _i1.SmartFake implements _i3.WiFiState {
  _FakeWiFiState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWifiAdvancedSettingsState_2 extends _i1.SmartFake
    implements _i4.WifiAdvancedSettingsState {
  _FakeWifiAdvancedSettingsState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGuestWiFiState_3 extends _i1.SmartFake
    implements _i5.GuestWiFiState {
  _FakeGuestWiFiState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMacFilteringState_4 extends _i1.SmartFake
    implements _i4.MacFilteringState {
  _FakeMacFilteringState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WifiListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWifiListNotifier extends _i2.Notifier<_i3.WiFiState> with _i1.Mock implements _i4.WifiListNotifier {
  @override
  _i2.NotifierProviderRef<_i3.WiFiState> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i3.WiFiState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeNotifierProviderRef_0<_i3.WiFiState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i3.WiFiState>);

  @override
  _i3.WiFiState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeWiFiState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeWiFiState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.WiFiState);

  @override
  set state(_i3.WiFiState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.WiFiState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeWiFiState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeWiFiState_1(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i3.WiFiState);

  @override
  _i6.Future<_i3.WiFiState> fetch([bool? force = false]) => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [force],
        ),
        returnValue: _i6.Future<_i3.WiFiState>.value(_FakeWiFiState_1(
          this,
          Invocation.method(
            #fetch,
            [force],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.WiFiState>.value(_FakeWiFiState_1(
          this,
          Invocation.method(
            #fetch,
            [force],
          ),
        )),
      ) as _i6.Future<_i3.WiFiState>);

  @override
  _i6.Future<_i3.WiFiState> save(_i7.WiFiListViewMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [mode],
        ),
        returnValue: _i6.Future<_i3.WiFiState>.value(_FakeWiFiState_1(
          this,
          Invocation.method(
            #save,
            [mode],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.WiFiState>.value(_FakeWiFiState_1(
          this,
          Invocation.method(
            #save,
            [mode],
          ),
        )),
      ) as _i6.Future<_i3.WiFiState>);

  @override
  _i6.Future<void> saveToggleEnabled({
    required List<String>? radios,
    required bool? enabled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveToggleEnabled,
          [],
          {
            #radios: radios,
            #enabled: enabled,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool checkingMLOSettingsConflicts(
    Map<_i4.WifiRadioBand, _i4.WiFiItem>? radios, {
    bool? isMloEnabled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkingMLOSettingsConflicts,
          [radios],
          {#isMloEnabled: isMloEnabled},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isAllBandsConsistent() => (super.noSuchMethod(
        Invocation.method(
          #isAllBandsConsistent,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int? checkIfChannelLegalWithWidth({
    required int? channel,
    required _i4.WifiChannelWidth? channelWidth,
    required _i4.WifiRadioBand? band,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIfChannelLegalWithWidth,
          [],
          {
            #channel: channel,
            #channelWidth: channelWidth,
            #band: band,
          },
        ),
        returnValueForMissingStub: null,
      ) as int?);

  @override
  void setWiFiSSID(
    String? ssid,
    _i4.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setWiFiSSID,
          [
            ssid,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWiFiPassword(
    String? password,
    _i4.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setWiFiPassword,
          [
            password,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWiFiEnabled(
    bool? isEnabled,
    _i4.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setWiFiEnabled,
          [
            isEnabled,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWiFiSecurityType(
    _i4.WifiSecurityType? type,
    _i4.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setWiFiSecurityType,
          [
            type,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWiFiMode(
    _i4.WifiWirelessMode? mode,
    _i4.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setWiFiMode,
          [
            mode,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEnableBoardcast(
    bool? isEnabled,
    _i4.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setEnableBoardcast,
          [
            isEnabled,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setChannelWidth(
    _i4.WifiChannelWidth? channelWidth,
    _i4.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setChannelWidth,
          [
            channelWidth,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setChannel(
    int? channel,
    _i4.WifiRadioBand? band,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setChannel,
          [
            channel,
            band,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i3.WiFiState? previous,
    _i3.WiFiState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [WifiAdvancedSettingsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWifiAdvancedSettingsNotifier extends _i2.Notifier<_i4.WifiAdvancedSettingsState> with _i1.Mock
    implements _i4.WifiAdvancedSettingsNotifier {
  @override
  _i2.NotifierProviderRef<_i4.WifiAdvancedSettingsState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i4.WifiAdvancedSettingsState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i4.WifiAdvancedSettingsState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i4.WifiAdvancedSettingsState>);

  @override
  _i4.WifiAdvancedSettingsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeWifiAdvancedSettingsState_2(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeWifiAdvancedSettingsState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.WifiAdvancedSettingsState);

  @override
  set state(_i4.WifiAdvancedSettingsState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.WifiAdvancedSettingsState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeWifiAdvancedSettingsState_2(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeWifiAdvancedSettingsState_2(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i4.WifiAdvancedSettingsState);

  @override
  _i6.Future<dynamic> fetch([bool? force = false]) => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [force],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  void setClientSteeringEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setClientSteeringEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNodesSteeringEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setNodesSteeringEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setIptvEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setIptvEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDFSEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setDFSEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMLOEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setMLOEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAirtimeFairnessEnabled(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setAirtimeFairnessEnabled,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i4.WifiAdvancedSettingsState? previous,
    _i4.WifiAdvancedSettingsState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [GuestWifiNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockGuestWifiNotifier extends _i2.Notifier<_i5.GuestWiFiState> with _i1.Mock implements _i8.GuestWifiNotifier {
  @override
  _i2.NotifierProviderRef<_i5.GuestWiFiState> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i5.GuestWiFiState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i5.GuestWiFiState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i5.GuestWiFiState>);

  @override
  _i5.GuestWiFiState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeGuestWiFiState_3(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeGuestWiFiState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.GuestWiFiState);

  @override
  set state(_i5.GuestWiFiState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.GuestWiFiState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeGuestWiFiState_3(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeGuestWiFiState_3(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i5.GuestWiFiState);

  @override
  _i6.Future<_i5.GuestWiFiState> fetch([bool? force = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [force],
        ),
        returnValue: _i6.Future<_i5.GuestWiFiState>.value(_FakeGuestWiFiState_3(
          this,
          Invocation.method(
            #fetch,
            [force],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i5.GuestWiFiState>.value(_FakeGuestWiFiState_3(
          this,
          Invocation.method(
            #fetch,
            [force],
          ),
        )),
      ) as _i6.Future<_i5.GuestWiFiState>);

  @override
  _i6.Future<_i5.GuestWiFiState> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i6.Future<_i5.GuestWiFiState>.value(_FakeGuestWiFiState_3(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i5.GuestWiFiState>.value(_FakeGuestWiFiState_3(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i6.Future<_i5.GuestWiFiState>);

  @override
  void setGuestSSID(String? ssid) => super.noSuchMethod(
        Invocation.method(
          #setGuestSSID,
          [ssid],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setGuestPassword(String? password) => super.noSuchMethod(
        Invocation.method(
          #setGuestPassword,
          [password],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEnable(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setEnable,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i5.GuestWiFiState? previous,
    _i5.GuestWiFiState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [MacFilteringNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMacFilteringNotifier extends _i2.Notifier<_i4.MacFilteringState> with _i1.Mock
    implements _i4.MacFilteringNotifier {
  @override
  _i2.NotifierProviderRef<_i4.MacFilteringState> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeNotifierProviderRef_0<_i4.MacFilteringState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeNotifierProviderRef_0<_i4.MacFilteringState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.NotifierProviderRef<_i4.MacFilteringState>);

  @override
  _i4.MacFilteringState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeMacFilteringState_4(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeMacFilteringState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.MacFilteringState);

  @override
  set state(_i4.MacFilteringState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.MacFilteringState build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeMacFilteringState_4(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeMacFilteringState_4(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i4.MacFilteringState);

  @override
  _i6.Future<_i4.MacFilteringState> fetch() => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
        ),
        returnValue:
            _i6.Future<_i4.MacFilteringState>.value(_FakeMacFilteringState_4(
          this,
          Invocation.method(
            #fetch,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.MacFilteringState>.value(_FakeMacFilteringState_4(
          this,
          Invocation.method(
            #fetch,
            [],
          ),
        )),
      ) as _i6.Future<_i4.MacFilteringState>);

  @override
  _i6.Future<dynamic> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  dynamic setEnable(bool? isEnabled) => super.noSuchMethod(
        Invocation.method(
          #setEnable,
          [isEnabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic setAccess(String? value) => super.noSuchMethod(
        Invocation.method(
          #setAccess,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic setSelection(List<String>? selections) => super.noSuchMethod(
        Invocation.method(
          #setSelection,
          [selections],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic removeSelection(List<String>? selection) => super.noSuchMethod(
        Invocation.method(
          #removeSelection,
          [selection],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i4.MacFilteringState? previous,
    _i4.MacFilteringState? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
